### ISSUE TITLE
Upload File extension validation

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#1]
Upload file in the Vendor Edit section doesn't check for the file extension properly. 
Eg: I have upload .txt file but still i get a error message saying 
Invalid extension. please find the image enclosed.

![image](https://cloud.githubusercontent.com/assets/20394163/19885073/ac0b6f18-a042-11e6-8131-69d3bbb1c75b.png)

**Comment by NaziniSK** [comment]
corrected this please close if its not reproducing

**Comment by bhargavibindhu** [comment]
@NaziniSK Yes file uploads are working. But take care of the alignment. Its very much clumsy.

![image](https://cloud.githubusercontent.com/assets/20394163/19965327/7f284f92-a1ec-11e6-970c-bb8b255538b7.png)

++++++++++++++++++++++++++++++++++++++++++++

**Please maintain the below format for all file uploads**
++++++++++++++++++++++++++++++++++++++++++++
![image](https://cloud.githubusercontent.com/assets/20394163/19965419/e6175af4-a1ec-11e6-9dab-caccbfed94e8.png)

**Comment by NaziniSK** [comment]
ok fine
