### ISSUE TITLE
Pagination For Search Records in Descending order

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#10]
![image](https://cloud.githubusercontent.com/assets/23167576/19888605/a6058b90-a055-11e6-9635-08993b1bfcd6.png)

Pagination in listing of Clients  is not working and showing only first 10 records when i click 25 .

**Comment by NaziniSK** [comment]
Corrected this please wait for next deployment .

**Comment by mounikaalladi** [comment]
Thanks Nazini Now it is Working

**Comment by mounikaalladi** [comment]
Record should Have to display in Descending order While searching Records like 10 ,20,30. For Vendor ,client and Consultant .

For vendor it should display in descending like this while we search 20 and so on..
![image](https://cloud.githubusercontent.com/assets/23167576/20051373/bb034534-a4f4-11e6-901d-1fe3e12e3ae8.png)

For client it should display in descending like this while we search 20 and so on..
![image](https://cloud.githubusercontent.com/assets/23167576/20051387/c8fc1936-a4f4-11e6-943f-f627296bd290.png)

For Consultant it should display in descending like this while we search 20 and so on..
![image](https://cloud.githubusercontent.com/assets/23167576/20051398/d3949058-a4f4-11e6-829f-3dbdcfac34e6.png)

**Comment by NaziniSK** [comment]
corrected this , please verify and close

![image](https://cloud.githubusercontent.com/assets/23185953/20091110/14e547ce-a5b7-11e6-9930-47c222fffcc1.png)
![Uploading image.png…]()

**Comment by bhargavibindhu** [comment]
1)   In Invoice page, the default pagecount is shown as 2 but it is showing more than 2 records.

2) It is not working for Invoice http://va.antronsys.com/VAModule/Invoices

The data listed is getting changed when the "pagecount" is changed.

Before changing the pagecount:
![image](https://cloud.githubusercontent.com/assets/20394163/20092586/f6e31848-a5be-11e6-9932-a9bee5e0379c.png)

After changing the pagecount: (the data listed is changed)
![image](https://cloud.githubusercontent.com/assets/20394163/20092613/20d9dcd6-a5bf-11e6-902a-9d124823b105.png)

**Comment by NaziniSK** [comment]
corrected this

**Comment by bhargavibindhu** [comment]
This is not fixed, please check again. The issue persists!!!

**Comment by mounikaalladi** [comment]
![image](https://cloud.githubusercontent.com/assets/23167576/20832638/5942236c-b8b1-11e6-96e3-ff283bb70be3.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20883119/7119400a-bb0a-11e6-8758-003181fec06e.png)

please provide steps to reproduce.

**Comment by mounikaalladi** [comment]
Regarding this issue we have discussed with nazini .She told that they work on that .

**Comment by NaziniSK** [comment]
corrected this issue

**Comment by NaziniSK** [comment]
followed same steps as @mounikaalladi explained, its working

**Comment by mounikaalladi** [comment]
working now
