### ISSUE TITLE
Consultant project details in dashboard

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#100]
Client has assigned only one project to consultant .But in dashbord it is showing
 In-progress-3 , completed-2
![image](https://cloud.githubusercontent.com/assets/11813145/20752348/f5b8488e-b726-11e6-973d-e3f305b69a78.png)

**Comment by NaziniSK** [comment]
for that one project five tasks are assigned 3 in-progress and 2-completed . 
All the tasks assigned for a particular project (project added for this consultant )will be shown here.

**Comment by sanndheep5005** [comment]
yes but for this consultant only one project is assigned . And it is showing 3-in progress and 2 completed

**Comment by NaziniSK** [comment]
![consultanttimesheet](https://cloud.githubusercontent.com/assets/23185953/20963492/93f63224-bc93-11e6-9ac0-0a74e9763b78.PNG)
![dashboard](https://cloud.githubusercontent.com/assets/23185953/20963495/989e4b18-bc93-11e6-931d-05e2095a387d.PNG)

Corrected this issue. For consultant 'rajasree' ,task assignment details and dashboard pictures are attached. Please check for your consultant logins.
