### ISSUE TITLE
Time Sheet approval

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#101]
When client approved the time sheet the data is saved but we are getting a error message saying some errors in reading consultant errors.
![image](https://cloud.githubusercontent.com/assets/11813145/20752658/717f64b0-b728-11e6-81bb-e67badce740d.png)

**Comment by NaziniSK** [comment]
please provide login details

**Comment by sanndheep5005** [comment]
When client approved the time sheet the data is saved but we are getting a error message saying some errors in reading consultant errors. dt : 5-12-16

![image](https://cloud.githubusercontent.com/assets/11813145/20886308/7801cc50-bb1b-11e6-8a93-9eaa9ad9e30c.png)

**Comment by NaziniSK** [comment]
corrected this
![Uploading image.png…]()

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20913511/81249ca8-bb9e-11e6-9de9-ed8ca5314182.png)
