### ISSUE TITLE
footer background not displaying in super admin consultant add page

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#102]
![image](https://cloud.githubusercontent.com/assets/11813145/20783308/fdb17370-b7b8-11e6-8bd9-00e244e14d66.png)

**Comment by sanndheep5005** [comment]
In vendor consultant add also footer background not displaying

![image](https://cloud.githubusercontent.com/assets/11813145/20884495/9e076f86-bb11-11e6-9c19-03dc5dc3987e.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20919843/bb785578-bbc3-11e6-893b-ef4afb7cc1a8.png)
corrected this
