### ISSUE TITLE
Login Error - BLOCKER

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#104]
We are not able to login as VASuperAdmin and it throws error at http://idpva.antronsys.com/oauth2/Login 
![image](https://cloud.githubusercontent.com/assets/20394163/20785856/7b502e2a-b7c8-11e6-9498-0d0238a07e45.png)

**# Please fix it and keep us posted as it is blocking our UAT.**

**Comment by mounikaalladi** [comment]
VASuperAdmin Login Screen Cant see all the modules when we login.
![image](https://cloud.githubusercontent.com/assets/23167576/20793208/e7da5ed0-b7eb-11e6-87b2-8839b128c6e9.png)

**Comment by bhargavibindhu** [comment]
This is a duplicate of 95 and hence closing it.
