### ISSUE TITLE
Error message description

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#105]
error message getting your data is in processing . But data is saved

![image](https://cloud.githubusercontent.com/assets/11813145/20792848/15605b9a-b7ea-11e6-98f8-42bb2c3d0476.png)

and in this page we are getting error message like invalid client details . But it should be "client details already exists".
![image](https://cloud.githubusercontent.com/assets/11813145/20792819/edc8b2da-b7e9-11e6-93c5-fab9b8f51b36.png)

**Comment by NaziniSK** [comment]
error message getting your data is in processing, this message is shown only when save is taking time or some fields like login name ,last name are not saved, u can check this by refreshing.
If saved then this message wont be showed .

**Comment by bhargavibindhu** [comment]
Antronsys will get back on this as per the discussion I had with Sandeep today morning.

**Comment by NaziniSK** [comment]
That error message is proper, as internally some fields are not updated in database so its showing that message . "Your data is processing please revisit this page later" .

Invalid client employee details error is corrected.

**Comment by sanndheep5005** [comment]
The error message is not displaying now its working
