### ISSUE TITLE
Icons at the Right panel - Green Top arrow, Chat, Ticket and Screenshare icons

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#107]
If we hover on Top arrow icon we are getting 3 icons 
1) **Chat icon** : please change the icon as chat icon.
2) **Ticket**  :
3) **screenshare** :  can u please explain  how these  works . Ticket and screen share

![image](https://cloud.githubusercontent.com/assets/11813145/20885024/9eda98c2-bb14-11e6-8baa-b18543f5fb48.png)

**Comment by NaziniSK** [comment]
chat and screen share are not implemented , in floating icons. 

you can raise tickets using ticket icon there.

**Comment by sanndheep5005** [comment]
ok Regarding this issue i have informed Bhargavi mam she will be discussing with sandeep sir.

**Comment by sandipkumarnandi** [comment]
We will take these icons off.

**Comment by sandipkumarnandi** [comment]
AS this is out of scope, chat has been moved to left hand side

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21003720/ec043e7e-bd52-11e6-80bb-6435200ee283.png)
removed floating icons

**Comment by sanndheep5005** [comment]
removed floating icon
