### ISSUE TITLE
Duplicate entries in Consultants module

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#108]
I have created rohanconsultant1 and saved the data and after few seconds once again saved the data . And when i am checking in consultants list . rohanconsultant1 is displayed twice

![image](https://cloud.githubusercontent.com/assets/11813145/20886129/8131ac38-bb1a-11e6-8860-1939a604a3cb.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20919612/bd881714-bbc2-11e6-96bd-44e75dfb5436.png)
corrected this

**Comment by NaziniSK** [comment]
it will check for consultant name and email id combination in consultant page
