### ISSUE TITLE
Phone number mentioned in Vendor Office and Billing details

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#109]
Is the phone number given in Office and Billing details pertains to the Vendor Admin? If yes, I don't see this when i am editing the Vendor admin details for the first time. If no, I see this phone number displayed in vendor edit for second time.

![image](https://cloud.githubusercontent.com/assets/23167576/20886115/68ffa44e-bb1a-11e6-8457-ed6ae700a859.png)

For First time Phone number Field is blank
![image](https://cloud.githubusercontent.com/assets/23167576/20886145/9578b59c-bb1a-11e6-9e39-9f44da08ae0a.png)

For second time saving in super Admin 
![image](https://cloud.githubusercontent.com/assets/23167576/20886203/e93f24b8-bb1a-11e6-8ad2-493bc7b09ba8.png)

IN Vendor Admin -Vendor employee edit After Refreshing page
![image](https://cloud.githubusercontent.com/assets/23167576/20886217/01d3aa12-bb1b-11e6-8a02-f0511debd7bc.png)

**Comment by NaziniSK** [comment]
its not vendor admin phone , its clearly mentioned as billing and office phone , but still why this confusion.
vendor Admin (personal phone ) will be added in vendor employee page( default vendor employee), initially this is not given , this should be added later in edit case .
vendor is not a single person here, it represents a company.


@mounikaalladi what is this first time and second time I didn't get you ? , is it for same record or different record ?, please provide steps to reproduce.

**Comment by mounikaalladi** [comment]
**It is for same record .**

**Comment by NaziniSK** [comment]
which record is it vendor employee or vendor . Please mention clearly

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20925518/84a52890-bbdd-11e6-8396-3b46281372e0.png)

this is first time (after vendor save)

![image](https://cloud.githubusercontent.com/assets/23185953/20925549/aae62220-bbdd-11e6-9849-e820728571d0.png)

second time (after vendor edit)

**Comment by NaziniSK** [comment]
corrected now

**Comment by sandipkumarnandi** [comment]
The office details are for the Main office and not for any individual. So please fix it.

**Comment by NaziniSK** [comment]
already corrected this issue yesterday.
