### ISSUE TITLE
Refresh button  Add Consultant 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#11]
![image](https://cloud.githubusercontent.com/assets/23167576/19888675/34dd1c8e-a056-11e6-964c-4e2208f2a455.png)

Refresh is not working in  Add Consultant Page

**Comment by mounikaalladi** [comment]
Refresh is not working

**Comment by mounikaalladi** [comment]
Have u fixed this

**Comment by NaziniSK** [comment]
corrected this please verify and close

**Comment by mounikaalladi** [comment]
K its working
