### ISSUE TITLE
Phone number mentioned in Client Office and billing details

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#110]
Is the phone number given in Office and Billing details pertains to the Client Admin? If yes, I don't see this when i am editing the Client admin details for the first time. If no, I see this phone number displayed in Client edit for second time.

![image](https://cloud.githubusercontent.com/assets/23167576/20886408/eb35db58-bb1b-11e6-8329-c6ec186f19ee.png)

For First time Phone number Field is blank
![image](https://cloud.githubusercontent.com/assets/23167576/20886418/f394f93c-bb1b-11e6-96df-d371ac956755.png)

For second time saving in super Admin 
![image](https://cloud.githubusercontent.com/assets/23167576/20886453/10120e92-bb1c-11e6-9d65-dfd5544b29ca.png)

IN Client Admin -Client employee edit After Refreshing page

![image](https://cloud.githubusercontent.com/assets/23167576/20886473/1bcb3042-bb1c-11e6-887e-7392094afb23.png)

**Comment by NaziniSK** [comment]
its not client admin phone , its clearly mentioned as billing and office phone , but still why this confusion.
client Admin (personal phone ) will be added in client employee page( default client employee), initially this is not given , this should be added later in edit case .
Client is not a single person here, it represents a company.

**Comment by mounikaalladi** [comment]
It is for same record

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20925672/26719a0a-bbde-11e6-857d-e5717130c8e1.png)
this is for first time (client save)

![image](https://cloud.githubusercontent.com/assets/23185953/20925701/52231fde-bbde-11e6-9f54-b0edefadd55b.png)
this is for second time(client edited and saved)

**Comment by sandipkumarnandi** [comment]
The office details are for the Main office and not for any individual. So please fix it.

**Comment by NaziniSK** [comment]
already corrected this issue
