### ISSUE TITLE
Alert box triggers in consultant add and edit page while adding skills

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#111]
If we type a skill in consultant add or edit page EX : php and without clicking add button if i press enter we are getting a alert box saying . Do you want to remove association of this consultant with current vendor?

![image](https://cloud.githubusercontent.com/assets/11813145/20886568/b49f42d6-bb1c-11e6-928a-e4fcb01b559f.png)

**Comment by mounikaalladi** [comment]
![image](https://cloud.githubusercontent.com/assets/23167576/20886718/60391676-bb1d-11e6-893a-991de19ea3da.png)

**Comment by NaziniSK** [comment]
this is corrected , please verify now
