### ISSUE TITLE
Exit Date issue while Inactivating Users

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#112]
Date given as joining  5th dec 2016 while i am inactivating  giving as 4th dec it is inactivating.
![image](https://cloud.githubusercontent.com/assets/23167576/20887210/c3556262-bb1f-11e6-9635-8b17ca3f17c1.png)

 Inactivating jyothi and given date of exit as 4th dec  .
![image](https://cloud.githubusercontent.com/assets/23167576/20887223/cdc90e74-bb1f-11e6-8940-e8506b3fb054.png)

After saving Inactivated 
![image](https://cloud.githubusercontent.com/assets/23167576/20887230/d4f650e4-bb1f-11e6-868d-dac91c9b2a0f.png)

**Comment by NaziniSK** [comment]
Exit date is different form contract end dates. Exit date is just to maintain a record when the user is deactivated, as inactivation is not permanent delete of consultant.

**Comment by mounikaalladi** [comment]
yes it is not permanent delete of consultant but it should not accept previous date while exiting .
 
Can u please Explain the functionality in detail how it works..??

**Comment by NaziniSK** [comment]
its just inactivation date, when you are inactivating this user , nothing else

**Comment by sandipkumarnandi** [comment]
This will be restricted for any date which is lesser than today's date.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21003384/146d2aa8-bd51-11e6-9847-2379d0773f12.png)
it wont accept dates lesser than today's date

![image](https://cloud.githubusercontent.com/assets/23185953/21003426/5547b278-bd51-11e6-8cf0-de5a6146ff1f.png)


![image](https://cloud.githubusercontent.com/assets/23185953/21003465/7f2761f6-bd51-11e6-9daf-8e55929cb8b9.png)

**Comment by mounikaalladi** [comment]
its working
