### ISSUE TITLE
Add or delete skills in consultant page

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#113]
![image](https://cloud.githubusercontent.com/assets/11813145/20887740/f1144766-bb21-11e6-9300-c472a1a0f8d4.png)
1) Added PHP
![image](https://cloud.githubusercontent.com/assets/11813145/20887770/0c0e9d0a-bb22-11e6-9f80-57f1a905d1ed.png)

2) deleted php
![image](https://cloud.githubusercontent.com/assets/11813145/20887815/374ee2e0-bb22-11e6-95e8-55fe0a4e0019.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20887864/65791668-bb22-11e6-8f60-5379bfa86ae9.png)

3) once again trying to add php getting error message
![image](https://cloud.githubusercontent.com/assets/11813145/20887902/90a115b6-bb22-11e6-800d-cd4908e70e29.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20912857/e94d2d6e-bb98-11e6-8e83-cc753aa2b2b9.png)
corrected this issue, please check the above screenshots

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20912886/258bd6a4-bb99-11e6-9f70-d11117d889fd.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20912888/2d9bfc98-bb99-11e6-853f-68ad6aa1908e.png)

**Comment by sanndheep5005** [comment]
working
