### ISSUE TITLE
add or delete Education and certifications in consultant page

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#114]
1) deleted graduation once again trying to add .getting error message.

![image](https://cloud.githubusercontent.com/assets/11813145/20888092/64cb8bbe-bb23-11e6-8159-43a10bc3eba3.png)

2) Added certification and deleted and once again trying to add getting error message

![image](https://cloud.githubusercontent.com/assets/11813145/20888163/ad4e26ee-bb23-11e6-8a18-9ff756c26800.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20925780/dbda0cce-bbde-11e6-879d-09bc6c704640.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20925786/e309bfda-bbde-11e6-818a-4379045e405a.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20925806/f767a8c0-bbde-11e6-8af3-44c4fa0288e1.png)
![Uploading image.png…]()

corrected the above issue
