### ISSUE TITLE
Admin List is missing

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#116]
Admin List as mentioned in the VAScreens4.pptx sent by you has the below screen. can you please help me in viewing this in http://va.antronsys.com/
![image](https://cloud.githubusercontent.com/assets/20394163/21477105/a81c93f8-cb64-11e6-90d6-57257c85b3c1.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21538171/2c0e8524-cdc0-11e6-8899-031937f96669.png)
added as dashboard item for super admin login

**Comment by bhargavibindhu** [comment]
Please find the screen given in https://github.com/acsestech/virtualassociate/issues/116#issue-197544656 
it describes the entity (vendor / client ) with permission type. What you have implemented is different from what is provided. Please check and revert.

**Comment by sandipkumarnandi** [comment]
Permission type field was initially put only for illustrating basic values if any user has access or not, whichhas been represented well as 'Active' which signified if user is active or inactive, there by helping the VASuperAdmin to decide whether to make any existing user Active who is Inactive currently.
