### ISSUE TITLE
ADD Consultant Client Details

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#12]
![image](https://cloud.githubusercontent.com/assets/23167576/19888835/398e3ca8-a057-11e6-9a51-e385a527c6a9.png)

While i tried to add Client Details for consultant in dropdown there are multiple times Client name (Client antronsys) are displaying.

**Comment by NaziniSK** [comment]
As client saved multiple times so here also it's shown multiple times .(both of these bugs are related solving one is enough)
![image](https://cloud.githubusercontent.com/assets/23185953/19916608/b2f6196e-a0e1-11e6-8108-8abc798def0d.png)

**Comment by mounikaalladi** [comment]
As per Now it is solved now If any issues occurs again then we will  re open it  as a bug.

![image](https://cloud.githubusercontent.com/assets/23167576/19957645/6014773a-a1be-11e6-85b2-caca17bace91.png)

**Comment by bhargavibindhu** [comment]
Closing it as per https://github.com/acsestech/virtualassociate/issues/12#issuecomment-258073131
