### ISSUE TITLE
Inactivate users

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#14]
I have turned a vendor admin as Inactive. But still i am able to login with its credentials.

Eg: I have turned the below user as inactive. But i am able to login using this credentials.
Login Name  : sindhuja
Password     : Sindhu@123

Can you explain in detail about this?

**Comment by mounikaalladi** [comment]
Then It is a Bug Mam

**Comment by NaziniSK** [comment]
If any user is made inactive , his/her login will be blocked , but this will take time ,so please wait ten seconds after making user inactive and try to login, if it is still allowing then it is a bug

**Comment by bhargavibindhu** [comment]
@NaziniSK Yes i have checked with logging of the inactive user after 10min. And still its getting logged in. Can you please check this?

**Comment by NaziniSK** [comment]
Please Check now, we started services by evening .

**Comment by bhargavibindhu** [comment]
I see this still occurring... Created a VendorAdmin username: AAAVendor and deactivated it. I tried to log in again with the AAAVendor credentials. It takes me inside the application.

**Comment by NaziniSK** [comment]
please wait for 10 to 20 seconds after making user inactive and then try to login

**Comment by mounikaalladi** [comment]
Inactive user is also logging in i also tried it

**Comment by NaziniSK** [comment]
I corrected this , please verify once
![image](https://cloud.githubusercontent.com/assets/23185953/20128682/d714a2f0-a66f-11e6-869e-866e48cf18fc.png)

**Comment by bhargavibindhu** [comment]
@NaziniSK I have tried it with Username: naresh123. I have deactivated it and it is listed in the deactivated list of users. 
After deactivating this user, I am still able to login with his credentials. This is checked after clearing cookies etc.

**Comment by mounikaalladi** [comment]
@NaziniSK Naresh is already is inactive mode but still i am getting option for "Inactivate", please find the image below.

![image](https://cloud.githubusercontent.com/assets/23167576/20130042/101e263e-a67a-11e6-89a0-02caa6d17890.png)

**Comment by NaziniSK** [comment]
@mounikaalladi  inactive should not be there in vendor employee what it means, is it not working ?

**Comment by NaziniSK** [comment]
corrected blocking logins if user is inactivated please verify and close if working

**Comment by bhargavibindhu** [comment]
Please give appropriate error message while logging in. I tried to login after deactivating the jesperclient. Now i am not able to login but the message is displayed as incorrect password. Please correct this.

![image](https://cloud.githubusercontent.com/assets/20394163/20213846/96db271e-a830-11e6-8b6e-0f4dd4c1c4ac.png)

**Comment by NaziniSK** [comment]
Functionality of Inactive is working , this is enhancement in showing proper message. please treat this seperately

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20253167/21efd7f8-aa4f-11e6-9b51-93440358671e.png)
corrected now please verify and close

**Comment by bhargavibindhu** [comment]
Ok, Revoke vendor admin is not working. Please check it.

**Comment by NaziniSK** [comment]
please raise it as separate bug mam, its very confusing for us

**Comment by mounikaalladi** [comment]
This issue is getting repeated 

Vendor Admin login like rajeev  have been in list of inactive records but also can login 
![image](https://cloud.githubusercontent.com/assets/23167576/20748431/200fb0b2-b714-11e6-9de6-47b80a94cf7e.png)

Rajeev Login Screen 
![image](https://cloud.githubusercontent.com/assets/23167576/20748486/5604c82e-b714-11e6-9e2e-c1431297fbbf.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20882976/aadcbb24-bb09-11e6-8841-918d60ce93d2.png)

Rajeev, we added while testing(in between correcting code ), so please don't consider that , try with newly added ones.

![image](https://cloud.githubusercontent.com/assets/23185953/20883049/0f3caf34-bb0a-11e6-964d-558011eba922.png)
