### ISSUE TITLE
Consultant data display in Vendor Admin Login 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#17]
![image](https://cloud.githubusercontent.com/assets/23167576/19889069/deedc302-a058-11e6-8d60-4fcb1e4c036f.png)

I just created new Vendor then the vendor dont have any consultants right defaultly it showing  two consultants in vendor login.

**Comment by mounikaalladi** [comment]
Error Labels Are shown But messages are not displaying Very difficult to find.

![image](https://cloud.githubusercontent.com/assets/23167576/20129107/860ccf1e-a673-11e6-9cff-8fb73d39125f.png)

**Comment by NaziniSK** [comment]
This issue is corrected , if still there please show me on skype or teamviewer

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20129203/286efe62-a674-11e6-8e27-18fdee6a5455.png)

for first error, logged in as vendor admin, no consultant are shown , because he is not under any consultant.
