### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#2]
![image](https://cloud.githubusercontent.com/assets/23167576/19884825/94b4f01a-a041-11e6-9bb9-75700ca58e25.png)

About While clicking add button the space should between the box and adding next item.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20001780/bab8df56-a2a3-11e6-9f0e-065ab94ad702.png)
corrected this , please check once

**Comment by mounikaalladi** [comment]
Its Working
