### ISSUE TITLE
Client Edit 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#21]
![image](https://cloud.githubusercontent.com/assets/23167576/19889401/b8bc2d5c-a05a-11e6-8421-9130ea65bc76.png)

Client Edit details are not dispalying for some records .

**Comment by NaziniSK** [comment]
Is this occurred for new entries which u added , or for old ones , if it is for old ones please ignore those , at that time background services were not working.

**Comment by mounikaalladi** [comment]
ok now its working
