### ISSUE TITLE
consultant add error

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#23]
![image](https://cloud.githubusercontent.com/assets/23167576/19889644/ff8b8f9c-a05b-11e6-9493-1f2e894f8b1f.png)

![image](https://cloud.githubusercontent.com/assets/23167576/19889656/146ad6de-a05c-11e6-9644-50b6f4b9193a.png)

I have added a new consultant in general i have given as Kishore( vendor ) and in vendor Details i have given another vendor name as Sindhuja and joining date and expiry date was not given but also saved

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20129430/9eae2a2a-a675-11e6-88ad-24405783dfd5.png)

corrected this

**Comment by mounikaalladi** [comment]
Its showing Empty error while clicking save 

![image](https://cloud.githubusercontent.com/assets/23167576/20129496/2ae9eb32-a676-11e6-83c7-3fc2cbd42b1e.png)

**Comment by NaziniSK** [comment]
![consultantsave](https://cloud.githubusercontent.com/assets/23185953/20294834/12c8cb26-ab27-11e6-8a06-037acb54c0c8.PNG)

Resolved this. Please check and verify

**Comment by mounikaalladi** [comment]
Created new consultant after saving the button was disabled and any message was not displayed .Like "Your data is processing please revisit this page later" or u r data is saved . But it can see in List of consultants

![image](https://cloud.githubusercontent.com/assets/23167576/20298747/a91f7820-ab3d-11e6-9d5e-032ef5727537.png)

**Comment by NaziniSK** [comment]
We are disabling the save button till  the save operation gets completed. When the save operation completed, we got 'Processing' and 'your data got saved' toasts correctly. Please clear cache and test again

**Comment by mounikaalladi** [comment]
When the save operation completed, we are unable to get  toast message .

![image](https://cloud.githubusercontent.com/assets/23167576/20338425/16998390-abfd-11e6-86ee-627dcb415035.png)

**Comment by NaziniSK** [comment]
![consultantsaveasva](https://cloud.githubusercontent.com/assets/23185953/20378960/7970a36e-acbf-11e6-936e-9a5c62925b09.png)
![consultantsaveassa](https://cloud.githubusercontent.com/assets/23185953/20378961/7972d616-acbf-11e6-9571-ac214f264956.png)

Tested Consultant adding by logging in as Vendor admin and Super admin. In both cases , getting toasts. Please check again.

**Comment by mounikaalladi** [comment]
Consultant add error again empty toast message while saving 
![image](https://cloud.githubusercontent.com/assets/23167576/20429214/472b5f26-adb3-11e6-8194-0471ff71f598.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20480739/dbfd872a-b009-11e6-8c6e-88d74a06a127.png)  [fireforx]
![image](https://cloud.githubusercontent.com/assets/23185953/20480836/498db3dc-b00a-11e6-8b18-94bf240e1a3e.png)[chrome]

![image](https://cloud.githubusercontent.com/assets/23185953/20481028/1245feba-b00b-11e6-97be-7556e5f7e114.png)[edge]

corrected this

**Comment by mounikaalladi** [comment]
Consultant ADD Error in super Admin  
empty toast message while clicking  save and but  saving  and showing in list of records 

![image](https://cloud.githubusercontent.com/assets/23167576/20886962/96f88be6-bb1e-11e6-8778-f85a954ac825.png)

Consultant edit error last name and login name was empty 
![image](https://cloud.githubusercontent.com/assets/23167576/20886988/b4b6de6c-bb1e-11e6-9034-5e72fb6d6e09.png)

Consultant add In vendor admin 
 Empty toast message while clicking  save and not saving  and  not showing in list of records 
![image](https://cloud.githubusercontent.com/assets/23167576/20886994/c3ae2178-bb1e-11e6-8c6e-5f16c27ac438.png)

**Comment by NaziniSK** [comment]
this is not reproducing

**Comment by mounikaalladi** [comment]
It is reproducing again empty toast messages
![image](https://cloud.githubusercontent.com/assets/23167576/21005441/d13c2860-bd5a-11e6-958f-59e4b4f0ab82.png)

**Comment by NaziniSK** [comment]
please check now

**Comment by mounikaalladi** [comment]
![image](https://cloud.githubusercontent.com/assets/23167576/21009566/5d4c382e-bd6d-11e6-9bb1-ae87093e667f.png)

![image](https://cloud.githubusercontent.com/assets/23167576/21009892/104e5f78-bd6f-11e6-89a3-1155018b80b2.png)

**Comment by mounikaalladi** [comment]
consultant save is properly working for now
