### ISSUE TITLE
Vendor employee add. # input fields

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#27]
Input fields are looking clumsy and send registraion link button overlapping input field.

![6ddafecf0cdb245e5184ced2d44886bf0c8262cb34c45c922c pimgpsh_mobile_save_distr](https://cloud.githubusercontent.com/assets/11813145/19920363/4c4287b2-a0fe-11e6-84df-53021047e388.jpg)

**Comment by NaziniSK** [comment]
corrected this
