### ISSUE TITLE
Vendor employee add other Contact

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#28]
![image](https://cloud.githubusercontent.com/assets/23167576/19920497/fd449078-a0fe-11e6-8473-e1cfe7e1047d.png)

The Other Contact Should not accept alphabets and should display the error message as phone number

**Comment by NaziniSK** [comment]
Other contact means not compulsory phone number , it might be any thing ,example: SkypeId

**Comment by bhargavibindhu** [comment]
@Nazini - Other contacts is a good idea. Please mention in the label as "Other Contacts (Skype)".
Because it might mean anything like phone num / email / linked in/ fb / skype etc. So please be specific.

**Comment by NaziniSK** [comment]
I just gave skype as example mam for your understanding purpose, it might be anything as you mentioned above . so how can we disallow alphabets in this context.

**Comment by bhargavibindhu** [comment]
Agreed, in that case how do i know what the user is mentioning here? if it is going to linked-in or fb or skype or phone num? Please make a work around on this and bring up a clarity.

**Comment by NaziniSK** [comment]
This is for reference, so in case its skype , it will be skype:sandipkumarnandi etc
so that people will know how to connect

![image](https://cloud.githubusercontent.com/assets/23185953/19960260/bd9ec4e2-a1d1-11e6-9b1f-9a0c1245b9b7.png)

**Comment by bhargavibindhu** [comment]
@NaziniSK then please specify the example format as above in the vendor employee form.

**Comment by NaziniSK** [comment]
its already done please verify once

**Comment by bhargavibindhu** [comment]
Works, closing it.
