### ISSUE TITLE
Vendor employee add  # overlapping

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#29]
Error message is overlapping with input field labels

![image](https://cloud.githubusercontent.com/assets/11813145/19920623/de240d12-a0ff-11e6-9ec1-35e70fe93c4b.jpg)

**Comment by NaziniSK** [comment]
corrected this

**Comment by mounikaalladi** [comment]
Done its corrected
![image](https://cloud.githubusercontent.com/assets/23167576/20089993/64ded774-a5b0-11e6-8777-18663ee9a6ec.png)
