### ISSUE TITLE
ui bugs

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#3]
1 )  ![image](https://cloud.githubusercontent.com/assets/11813145/19884934/01c6d600-a042-11e6-9c40-c110849f346f.png)

**Description**
After login when we click on vendors (or) clients (or) consultants .In these pages side bar menu and content box are not in a same row. content area is little bit down.

**Comment by NaziniSK** [comment]
corrected this.

**Comment by sanndheep5005** [comment]
Ok

**Comment by sanndheep5005** [comment]
<div  class="page-sidebar navbar-collapse collapse" style="margin-top:10px !important">

please make margin-top:14px; and check once

**Comment by NaziniSK** [comment]
sorry I didn't get you , please attach screen shot  about the issue

**Comment by sanndheep5005** [comment]
sidebar menu is little bit up compare to content box 

![image](https://cloud.githubusercontent.com/assets/11813145/19965047/1e6df446-a1eb-11e6-9b8d-c159d9a71142.png)

**Comment by NaziniSK** [comment]
Corrected this.Please check now

![image](https://cloud.githubusercontent.com/assets/23185953/20138774/56bf512a-a6a8-11e6-871c-487c81a05de2.png)
