### ISSUE TITLE
Vendor Employee add Phone number

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#30]
![image](https://cloud.githubusercontent.com/assets/23167576/19921029/fa5ded16-a101-11e6-8ba4-527e681ff9af.png)

phone number should accept atleast 6 and above it should not take 4 numbers only while saving .

**Comment by NaziniSK** [comment]
corrected this

**Comment by mounikaalladi** [comment]
Not Corrected this it was accepting  3 also

![image](https://cloud.githubusercontent.com/assets/23167576/19958849/5793c52a-a1c8-11e6-8014-66f8a1ea88e2.png)

**Comment by NaziniSK** [comment]
we have to deploy , please wait.....

**Comment by NaziniSK** [comment]
please revisit this bug

**Comment by mounikaalladi** [comment]
Phone have must and should take atleast 10  not taking less than 10 is this right ..??? please check this comment and close it mam if it is correct
![image](https://cloud.githubusercontent.com/assets/23167576/19965711/583d8bd4-a1ee-11e6-8243-f27a10a3ba8e.png)

**Comment by bhargavibindhu** [comment]
Please implement the phone number validation as @mounikaalladi has mentioned. It is also accepting alphabets, refer below.

![image](https://cloud.githubusercontent.com/assets/20394163/20053994/f7915ebc-a500-11e6-8f75-f672ce3100f4.png)

**Comment by sandipkumarnandi** [comment]
On focus out it will validate on focus out.

![image](https://cloud.githubusercontent.com/assets/23306567/20087857/36914a0e-a5a2-11e6-8335-c5b402bcaa04.png)

**Comment by mounikaalladi** [comment]
Phone number validation is implemented only in Vendor and Vendor Employee Add / Edit. Please implement it in Client and Consultant as well.

**Comment by NaziniSK** [comment]
Please check now 

![image](https://cloud.githubusercontent.com/assets/23185953/20133489/c2467c22-a68d-11e6-8de6-1fbc13ffa697.png)

![image](https://cloud.githubusercontent.com/assets/23185953/20133500/d3053396-a68d-11e6-9878-816bec455086.png)

**Comment by bhargavibindhu** [comment]
When i enter phone number less than 10 digits, the phone number validation message is displayed as "Please enter atleast 10 characters". But however the form is getting saved. Please see that the form data is not saved if you have any validation error messages in the screen. Screenshot below:

**Comment by sanndheep5005** [comment]
![image](https://cloud.githubusercontent.com/assets/11813145/20208519/b6d6c044-a814-11e6-8fa6-251e78790194.png)

**Comment by NaziniSK** [comment]
For form validations if any error occurred means we added like this, please check now
![image](https://cloud.githubusercontent.com/assets/23185953/20213383/6f6c08da-a82e-11e6-9f4b-6c204d3c78a4.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20213514/05f9a7c6-a82f-11e6-8426-f1586d542961.png)
