### ISSUE TITLE
Consultant Add in vendor Employee Login dropdown 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#31]
![image](https://cloud.githubusercontent.com/assets/23167576/19921414/d72153d6-a103-11e6-9000-64b82c934950.png)

Consultant Add in vendor Employee Login dropdown vendors are not coming.

**Comment by mounikaalladi** [comment]
Not Working 

![image](https://cloud.githubusercontent.com/assets/23167576/19959440/e3bea412-a1cc-11e6-9711-23081d3211af.png)

**Comment by NaziniSK** [comment]
vendor employee doesn't have permission to create or update or delete consultant. Actually in vendor employee login user should not be redirected to this page on click of add or edit button .
we are looking into that issue

**Comment by NaziniSK** [comment]
![capture](https://cloud.githubusercontent.com/assets/23185953/20165015/9b716c86-a72f-11e6-9d29-b94558b7fc56.PNG)
![untitled](https://cloud.githubusercontent.com/assets/23185953/20165030/ba3bb68a-a72f-11e6-827a-c13fa3043766.png)
![delete](https://cloud.githubusercontent.com/assets/23185953/20165035/d0514c78-a72f-11e6-85e1-37b4270b3248.PNG)

**Comment by NaziniSK** [comment]
![delete](https://cloud.githubusercontent.com/assets/23185953/20165050/ec1bacdc-a72f-11e6-9c4c-185cc5357388.PNG)
![untitled](https://cloud.githubusercontent.com/assets/23185953/20165051/ec1f950e-a72f-11e6-9748-2e0ef22c1ea2.png)
![create](https://cloud.githubusercontent.com/assets/23185953/20165065/0d152d14-a730-11e6-9080-338bb2240466.PNG)

**Comment by NaziniSK** [comment]
When vendor employee logs in, he can just see list page and view details by clicking on the name. Add Button (+ icon), Edit button, and delete button will not allow to perform the Add/Edit/Delete. Instead we will give toasts as in the previous images

**Comment by mounikaalladi** [comment]
Not Working

**Comment by NaziniSK** [comment]
HariPrasad is a vendor employee. Login name is hariprasad.

![hariaddedit](https://cloud.githubusercontent.com/assets/23185953/20294917/a0a2f318-ab27-11e6-8d2b-861b3baa1297.PNG)

When he logs in he can view the list page, and he can see list page and view details for a consultant

![clist](https://cloud.githubusercontent.com/assets/23185953/20294944/d9fbc6b2-ab27-11e6-8585-f3bfcd811349.PNG)

![view](https://cloud.githubusercontent.com/assets/23185953/20294951/f26a9962-ab27-11e6-8a30-97467fbb847b.PNG)

On click of ADD/EDIT/DELETE we are just getting toasts as in previous images. Please clear cache and test again

**Comment by mounikaalladi** [comment]
Login name: mouni password : Sandip@9

Vendor employee able to Edit the consultant details .

![image](https://cloud.githubusercontent.com/assets/23167576/20339265/55cd863e-ac01-11e6-9a56-90f36b647e66.png)

![image](https://cloud.githubusercontent.com/assets/23167576/20339448/67579a92-ac02-11e6-859d-16bc745c5355.png)

**Comment by mounikaalladi** [comment]
First i have attached two records and saved .
![image](https://cloud.githubusercontent.com/assets/23167576/20344016/fa2d749a-ac16-11e6-97e2-339e455d3e29.png)

Once again  i attached 2 records and saved.
![image](https://cloud.githubusercontent.com/assets/23167576/20344095/54e741e0-ac17-11e6-979b-1acdcdbe073f.png)

and then i have deleted those 2 records which i have added secondly.
![image](https://cloud.githubusercontent.com/assets/23167576/20344110/666b2aee-ac17-11e6-9fff-836085244d53.png)

 and then saved .
![image](https://cloud.githubusercontent.com/assets/23167576/20344117/6f8e2d24-ac17-11e6-93a0-3fb3366212b3.png)

After refreshed the page there i can see the previously deleted records.
![image](https://cloud.githubusercontent.com/assets/23167576/20344127/79706370-ac17-11e6-8ab7-3dda743eaa30.png)
