### ISSUE TITLE
Project status dasboard

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#32]
The dashboard says that there is no In-progress tasks and it is 0. On the contrary the over due tasks is labelled as 1. How is this calculated? Please explain.

![image](https://cloud.githubusercontent.com/assets/20394163/19924188/e5e8f5b0-a110-11e6-984f-6fcefe0ba13f.png)

**Comment by NaziniSK** [comment]
It is based on current month's tasks which were added in task assignment page .

**Comment by bhargavibindhu** [comment]
Will check it after Client module demo is done. parking it for now.

**Comment by bhargavibindhu** [comment]
linking this with #81 , i can verify this ticket only after 81 is fixed.

**Comment by bhargavibindhu** [comment]
Task Assignment is not updated in Dashboard.

Eg: technosoft is the client. He has assigned tasks to the consultants. But this is not seen in the dashboard.
![image](https://cloud.githubusercontent.com/assets/20394163/20825486/6874660a-b88a-11e6-9a39-f8b366def73b.png)


![image](https://cloud.githubusercontent.com/assets/20394163/20825493/7848f8de-b88a-11e6-917c-4f7ffa2da300.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20882703/35f0e5e8-bb08-11e6-8256-67c92ecb32fa.png)
