### ISSUE TITLE
UI Bug When clicking Pagination 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#33]
UI Bug When clicking Pagination 31 last record when i click on 30 its fyn .
![image](https://cloud.githubusercontent.com/assets/23167576/19927221/bf8b7772-a11e-11e6-83b8-a40a9fbcfaa7.png)

After clicking 31st record 
![image](https://cloud.githubusercontent.com/assets/23167576/19926782/968db364-a11c-11e6-866e-cee1ce7e33dd.png)

**Comment by NaziniSK** [comment]
corrected please verify
