### ISSUE TITLE
UI bugs or Vendor Add 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#34]
**Vendor Add General**
 
The Description field name is movieng left and Error Message should come down of the Input Box

![image](https://cloud.githubusercontent.com/assets/23167576/19927708/e8636e50-a120-11e6-9154-f40e07aa20c7.png)

**Vendor Add Bank Details**

The more space is coming between the two fields
![image](https://cloud.githubusercontent.com/assets/23167576/19927830/897f3c7e-a121-11e6-8608-c67c7792c1b8.png)

**Vendor Add Vendor Admin Details** 

Before entering the Last name the screen shot
![image](https://cloud.githubusercontent.com/assets/23167576/19927104/4ce2b3c0-a11e-11e6-913d-975932352157.png)

After entering the last name 
![image](https://cloud.githubusercontent.com/assets/23167576/19927553/2fe9e9ee-a120-11e6-816f-f80e3a5c1b97.png)

Then After Entering Email
![image](https://cloud.githubusercontent.com/assets/23167576/19927571/4bf0b0b4-a120-11e6-94b6-cf1c5d2e1e8d.png)

**Comment by NaziniSK** [comment]
corrected this issue, please check once today

**Comment by mounikaalladi** [comment]
ok Thanks Nazini it corrected
