### ISSUE TITLE
Vendor add Is not saving 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#35]
Vendor add is not saving When i add attachment 

![image](https://cloud.githubusercontent.com/assets/23167576/19928570/f6e63dfa-a124-11e6-85f6-09e28a34c097.png)

Vendor add is not saving When i add With out an attachment 

![image](https://cloud.githubusercontent.com/assets/23167576/19928619/320d981a-a125-11e6-90fd-7a97fc7de559.png)

I filled all the details and subtitted also then it is displaying as invalid endor details

![image](https://cloud.githubusercontent.com/assets/23167576/19928658/65a80962-a125-11e6-9ba7-fcfad1a02c4e.png)

**Comment by NaziniSK** [comment]
Please try with out adding attachments, to know whether r u still getting same error "Invalid Vendor Details".

I know attachment is having issue I am looking into it , but please check this once.

**Comment by bhargavibindhu** [comment]
Recommend @NaziniSK to implement the attachment in Vendor module jus like the one in client module. Example is given below.

![image](https://cloud.githubusercontent.com/assets/20394163/19959222/15730f54-a1cb-11e6-99df-8280d0afc8ec.png)

**Comment by NaziniSK** [comment]
corrected this 
![image](https://cloud.githubusercontent.com/assets/23185953/19964465/cd7885cc-a1e7-11e6-8937-097a07a86412.png)

**Comment by NaziniSK** [comment]
please check this now , if your still facing this issue , please show me in team viewer or skype

**Comment by mounikaalladi** [comment]
Reference #17  #61

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20129338/f1648bde-a674-11e6-8b9e-a8522ab205f0.png)
I attached a file and just now added an entry , it got saved for me

**Comment by bhargavibindhu** [comment]
Marked as duplicate and it is same as #61 please do the needful.

**Comment by mounikaalladi** [comment]
Newly Created these vendor details while editing  we unable to see only vendor admin details.

![image](https://cloud.githubusercontent.com/assets/23167576/20298254/d482f54e-ab3a-11e6-96a3-d1ab99922aae.png)

the message it displayed while saving "Your data is processing please revisit this page later " then we waited for half n hour then also we cant see vendor admin details

![image](https://cloud.githubusercontent.com/assets/23167576/20298488/3aa0bb26-ab3c-11e6-9f27-79184ac81903.png)

**Comment by mounikaalladi** [comment]
Vendor Add is not saving given correct details and displaying empty toast message while saving.

![image](https://cloud.githubusercontent.com/assets/23167576/20339708/e405b488-ac03-11e6-8e13-17669114a396.png)

**Comment by mounikaalladi** [comment]
Refresh is not working and sometimes unable to save 
![image](https://cloud.githubusercontent.com/assets/23167576/20342952/888af2a8-ac12-11e6-9798-caab239db7ab.png)

**Comment by NaziniSK** [comment]
this got saved for me
![image](https://cloud.githubusercontent.com/assets/23185953/20346198/d48eb136-ac20-11e6-814f-62932c5ce796.png)

check this vendor "vendorTest" I saved just now

**Comment by NaziniSK** [comment]
Refresh is corrected .Add am not getting that toast error
