### ISSUE TITLE
Account Logoff shows error

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#36]
When i log off from the account, i get the blocker showing error like below.

![image](https://cloud.githubusercontent.com/assets/20394163/19929150/fb312fd4-a127-11e6-9e19-4aaede5d5cb7.png)

**Comment by NaziniSK** [comment]
need to know the steps for reproducing it

**Comment by bhargavibindhu** [comment]
@NaziniSK This issue is not happening now, hence closing it. If this issue occurs then will reopen the thread. Thanks.
