### ISSUE TITLE
In myprofile #buttons

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#37]
Buttons are overlapping input fields

![image](https://cloud.githubusercontent.com/assets/11813145/19958304/3d67292a-a1c4-11e6-9678-b262ad7a450d.png)

**Comment by NaziniSK** [comment]
corrected this

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/19964643/ecba32d6-a1e8-11e6-9339-07ebef11ba88.png)
