### ISSUE TITLE
reset and forgot psswrd 

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#38]
icon r button  not displaying before Your account password has been successfully reset. To login click here
for both reset password and forgot password

![image](https://cloud.githubusercontent.com/assets/11813145/19959038/b126d806-a1c9-11e6-8594-a3a4cde4ce93.png)

![image](https://cloud.githubusercontent.com/assets/11813145/19959125/49adc238-a1ca-11e6-8468-3aa18c90e305.png)

**Comment by NaziniSK** [comment]
removed this icon please check in next deployment.
