### ISSUE TITLE
reset and forgot password #mozilla

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#39]
border is appearing around the text ( The password recovery link has expired. Please generate a new link.)
for reset  and forgot password
![image](https://cloud.githubusercontent.com/assets/11813145/19959230/20cff470-a1cb-11e6-8e07-893cf625ec35.png)

![image](https://cloud.githubusercontent.com/assets/11813145/19959301/9841ec7a-a1cb-11e6-9aef-e4b131511557.png)

**Comment by NaziniSK** [comment]
corrected this please verify once
