### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#4]
Pagination in listing of vendors / clients is always fixed as "2" as seen in the image below.

As seen in the pic, initially 24 records are found. but only 2 is selected always.

![image](https://cloud.githubusercontent.com/assets/20394163/19887704/0e97f8e2-a050-11e6-8656-27e38da6f45b.png)

**Comment by NaziniSK** [comment]
Corrected this please wait for next deployment

**Comment by bhargavibindhu** [comment]
Thanks, it works
