### ISSUE TITLE
selected 40 records alignment of records disturbed

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#40]
I have selected 40 records in one page and page is displaying as shown in the images . google ,safarai , ie10 , mozilla

![image](https://cloud.githubusercontent.com/assets/11813145/19961192/36ed4c74-a1d7-11e6-85c7-53084b09c2d7.png)

![image](https://cloud.githubusercontent.com/assets/11813145/19961102/c2b62ca4-a1d6-11e6-9801-a9a5e82097c1.png)

![image](https://cloud.githubusercontent.com/assets/11813145/19962586/6bdace28-a1de-11e6-9c69-68816d67f676.png)

![image](https://cloud.githubusercontent.com/assets/11813145/19962522/14bffa6e-a1de-11e6-940b-9f02e33a1864.png)

**Comment by NaziniSK** [comment]
corrected this , please verify once

**Comment by bhargavibindhu** [comment]
This is still occurring 

![image](https://cloud.githubusercontent.com/assets/20394163/19965738/70e5ec30-a1ee-11e6-9438-b784fee990b5.png)

**Comment by NaziniSK** [comment]
is this occurring in all browsers, I checked in google chrome
![image](https://cloud.githubusercontent.com/assets/23185953/19965911/4437e7b4-a1ef-11e6-90dd-c77a90894277.png)

**Comment by NaziniSK** [comment]
edge.
![image](https://cloud.githubusercontent.com/assets/23185953/19966052/fb5f1c64-a1ef-11e6-8c4f-4f3125fd935e.png)

**Comment by bhargavibindhu** [comment]
It is not working with the below resolution

![image](https://cloud.githubusercontent.com/assets/20394163/19966565/4e0b753c-a1f2-11e6-88d2-2a0832a70522.png)

**Comment by bhargavibindhu** [comment]
It is not working with the below resolution

![image](https://cloud.githubusercontent.com/assets/20394163/19966565/4e0b753c-a1f2-11e6-88d2-2a0832a70522.png)

**Comment by NaziniSK** [comment]
#33 ,think both are same , please merge as one

**Comment by sandipkumarnandi** [comment]
The resolution supported is HD (1366 x 768) you can try Ctrl + (-) to reduce the size and see

**Comment by bhargavibindhu** [comment]
This works with 1280 \* 800 resolution itself hence closed it.

**Comment by sanndheep5005** [comment]
ok mam and 33 also same issue
