### ISSUE TITLE
Vendor Admin Login Consultant Default Entries

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#42]
![image](https://cloud.githubusercontent.com/assets/23167576/19962733/0b98a3f4-a1df-11e6-8d1a-4c31cf0db7ca.png)

I created new Vendor Just Now And Got 2 Consultants Defaultly without adding consultants .

**Comment by NaziniSK** [comment]
same bug raising again and again?

**Comment by bhargavibindhu** [comment]
Closing this bug as it is duplicate of #17
