### ISSUE TITLE
Labeling in all the forms to copy office details to billing details

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#43]
Please provide a labeling like below to copy the office details to billing details. Make this change whereever required.

![image](https://cloud.githubusercontent.com/assets/20394163/19962874/b5aeae24-a1df-11e6-8f7c-5b5dfa8e5d52.png)

**Comment by NaziniSK** [comment]
Corrected , please check in next deployment.

**Comment by bhargavibindhu** [comment]
Please leave a space between the checkbox and the text "Same as office details".

**Comment by NaziniSK** [comment]
Corrected
