### ISSUE TITLE
Reset Password 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#44]
New password and Confirm password are not comparing 
Without entering confirm password also it is saving 
 Your account password has been successfully reset.

![image](https://cloud.githubusercontent.com/assets/23167576/19962963/44886784-a1e0-11e6-8f7f-b1acd24afa05.png)

**Comment by NaziniSK** [comment]
corrected this bug , please verify once

**Comment by mounikaalladi** [comment]
THis is working but displaying message should be corrected

The message displaying as confirm password is different from new password it should have to match the password right..??

![image](https://cloud.githubusercontent.com/assets/23167576/20052662/f90441c0-a4fa-11e6-9d3f-5c0960ff2052.png)

**Comment by NaziniSK** [comment]
how it will match the password . if we enter both same it will continue the process other wise its showing you the error message.

**Comment by mounikaalladi** [comment]
K i am closing the issue
