### ISSUE TITLE
profile image 

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#46]
profile image not displaying properly in mozilla , ie10, safari

1)  Google   
![image](https://cloud.githubusercontent.com/assets/11813145/19962905/eea44e82-a1df-11e6-880a-0bf50a6f330f.png)

2) IE10
![image](https://cloud.githubusercontent.com/assets/11813145/19962910/facb6ede-a1df-11e6-858a-d2089f957e27.png)

3) Mozilla
![image](https://cloud.githubusercontent.com/assets/11813145/19962982/5d1305b6-a1e0-11e6-9cb0-0714daaf7615.png)

4) safari
![image](https://cloud.githubusercontent.com/assets/11813145/19963055/bde4bcc2-a1e0-11e6-8767-e634a004a360.png)

**Comment by NaziniSK** [comment]
corrected this. wait for deployment

**Comment by sanndheep5005** [comment]
ok

**Comment by NaziniSK** [comment]
we are giving the message by saying that file upload/image upload won't support in safari
