### ISSUE TITLE
Client Registration mail

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#48]
Client Registration mail doesnt include the link to set the password. 
When we click http://va.antronsys.com it takes us only to the login page but not the password setting page.

![image](https://cloud.githubusercontent.com/assets/20394163/19963532/ca5d5070-a1e2-11e6-965a-650d8e9f242e.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20000845/8494d41a-a29f-11e6-9b2e-b563e3adbd3d.png)
Added like this please verify in next deployment.

**Comment by bhargavibindhu** [comment]
Please use the below format for the mail:

++++++++++++++++++++++++++++++++
Hello Ms.clientNazini clientNazini,
Greetings from Virtual Associates,

Your Username: clientNazini122

Please follow the below link to set your password.
Reset Password button
or 
Copy paste the url into your same browser:
idpva.antronsys.com/oauth2/ResetPassword?loginName=...........................

Thankyou,
Virtual Associates Team,
http://va.antronsys.com

**Comment by NaziniSK** [comment]
The above reset password link is auto generated , so we changed like this now.
![image](https://cloud.githubusercontent.com/assets/23185953/20086251/c4d35b62-a594-11e6-9007-c5687adf6d42.png)

![image](https://cloud.githubusercontent.com/assets/23185953/20086432/39f1d4f4-a596-11e6-8b4f-bb7312bfb64f.png)
