### ISSUE TITLE
Profile images not uploaded / saved

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#49]
Profile images are not uploaded with SuperAdmin / Vendor / client / consultant. Please maintain the aspect ratio for the image uploaded.

![image](https://cloud.githubusercontent.com/assets/20394163/19963979/0d2fd268-a1e5-11e6-9a78-7d04bd613222.png)

**Comment by NaziniSK** [comment]
what was the issue , is it not saving or alignment?

**Comment by bhargavibindhu** [comment]
Both saving and aspect ratio are the issue here. Please take care of it.

**Comment by NaziniSK** [comment]
We are specifying the size of photograph need to be uploaded .
