### ISSUE TITLE
Vendor Employee data display

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#5]
In Vendor employee data display, if there is no data for any column then please leave it empty. In the below pic, the designation is "Enter employee designation" which should not be displayed.

![image](https://cloud.githubusercontent.com/assets/20394163/19887909/502d365e-a051-11e6-9ad2-7a212c421924.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/19995912/7dd94c8c-a281-11e6-99c7-99b8f7648de4.png)
corrected this, for default entries it will be blank

**Comment by NaziniSK** [comment]
please check in next deployment

**Comment by bhargavibindhu** [comment]
Thanks, its done.
