### ISSUE TITLE
About History Question 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#50]
Vendor and Client has History button 
![image](https://cloud.githubusercontent.com/assets/23167576/19963154/2369ff30-a1e1-11e6-9259-2c54aa7272c7.png)

For Consultant does  History button  Required or not 
![image](https://cloud.githubusercontent.com/assets/23167576/19963163/2b3f1560-a1e1-11e6-8ea7-4a248bbd0da0.png)

**Comment by bhargavibindhu** [comment]
for Consultant, please add History button. @NaziniSK

**Comment by NaziniSK** [comment]
Added History button for consultant

**Comment by mounikaalladi** [comment]
k will move to Closed
