### ISSUE TITLE
Dublicate entries  are shown in dropdown  skill

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#51]
Skill dropdown getting Multiple Entries 

![image](https://cloud.githubusercontent.com/assets/23167576/19964060/8932779e-a1e5-11e6-9c4a-49c71abc880c.png)

When i add skill Same skill multiple Entries are taking 

![image](https://cloud.githubusercontent.com/assets/23167576/19964143/19a9d7f4-a1e6-11e6-8695-cb5a11713e08.png)

**Comment by NaziniSK** [comment]
corrected this

**Comment by mounikaalladi** [comment]
it Is reproducing again 
![image](https://cloud.githubusercontent.com/assets/23167576/20090371/c0d5fa60-a5b2-11e6-8411-f26ffab4b1d6.png)

**Comment by NaziniSK** [comment]
![vendorskill](https://cloud.githubusercontent.com/assets/23185953/20176471/f1d1a09e-a76d-11e6-8299-49e7c34a52ba.png)

Corrected . Please verify

**Comment by mounikaalladi** [comment]
Still not Working We keep it in a observation
