### ISSUE TITLE
In Vendor Admin  Add/Edit Consultant Save issue

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#52]
in Vendor Admin add consultant  Details are saving but pop up message is  showing as empty pop up Box 

![image](https://cloud.githubusercontent.com/assets/23167576/19964525/36286d1c-a1e8-11e6-9cf8-2b366db13074.png)

**Comment by NaziniSK** [comment]
It is already fixed ,please verify and close

**Comment by mounikaalladi** [comment]
refer  #23

**Comment by mounikaalladi** [comment]
while saving empty popup box is getting in  vendor admin Consultant add
![image](https://cloud.githubusercontent.com/assets/23167576/20830374/37891c68-b8a6-11e6-898b-74c1231e15e5.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20882622/e5cf2f3e-bb07-11e6-840a-2715e591c9ae.png)
its not reproducing

**Comment by mounikaalladi** [comment]
Refer #23

**Comment by mounikaalladi** [comment]
its working
