### ISSUE TITLE
 vendor admin Add/ Edit consultant Date Of Birth issue 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#53]
Date of Birth should have restrictions  ( like 20yrs above  ) it is accepting Todays date also .

![image](https://cloud.githubusercontent.com/assets/23167576/19964791/c81153c8-a1e9-11e6-96ce-e849c67a45aa.png)

**Comment by mounikaalladi** [comment]
This is Not implemented for user Profiles 
![image](https://cloud.githubusercontent.com/assets/23167576/20130910/06c166a4-a680-11e6-988b-bb5da25db437.png)

**Comment by NaziniSK** [comment]
added validations for birth date pls.. check now

![image](https://cloud.githubusercontent.com/assets/23185953/20138223/2c756510-a6a5-11e6-8f08-3809b62005ba.png)

**Comment by bhargavibindhu** [comment]
This is not fixed, please check again in "Approve User profiles".

**Comment by mounikaalladi** [comment]
DOB is  accepting today's date  also it should be like 20 yrs and above. 

![image](https://cloud.githubusercontent.com/assets/23167576/20338590/fbdb4b46-abfd-11e6-8b39-4f1fdcaa08c0.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20345478/5fba4314-ac1d-11e6-8662-530c7ca8c240.png)

corrected this in approval page

**Comment by mounikaalladi** [comment]
approve user profile is not working  

![image](https://cloud.githubusercontent.com/assets/23167576/20830412/5c49ce12-b8a6-11e6-962d-140bc87ad849.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20882400/cb404e2e-bb06-11e6-8459-1aa2c3a0a38a.png)
it is showing.

**Comment by mounikaalladi** [comment]
Approve user profile is not worked 2 days back .
That's why i unable to check the functionality of DOB.

**Comment by NaziniSK** [comment]
vendor admin Add/ Edit consultant Date Of Birth issue  , how is this related to approval page?
As approval user profile page issues are raised as separate bug #84

**Comment by mounikaalladi** [comment]
issue corrected in consultant but  i don't know about approve user profile page

**Comment by bhargavibindhu** [comment]
Closing as per consultant page
