### ISSUE TITLE
About Skills in Vendor and consultant should have same Functionality

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#54]
About Skills in Vendor and consultant Should have same funtionality 
Like PHP is not seen dropdown skill in vendor add 

![image](https://cloud.githubusercontent.com/assets/23167576/19965403/d0aa94d8-a1ec-11e6-9721-ac5a40d9d205.png)

 PHP is seen in dropdown skill  of  Consultant  add 

![image](https://cloud.githubusercontent.com/assets/23167576/19965353/994e8530-a1ec-11e6-828a-ef371d4994a0.png)

**Comment by NaziniSK** [comment]
corrected this

**Comment by mounikaalladi** [comment]
still Not working 
Vendor ADD
![image](https://cloud.githubusercontent.com/assets/23167576/20130783/27529b50-a67f-11e6-92ad-4ad74cc43dbe.png)

Consultant ADD
![image](https://cloud.githubusercontent.com/assets/23167576/20130810/5dfdae2e-a67f-11e6-890e-381f3d520589.png)
