### ISSUE TITLE
gap between select field and education type box #safari

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#56]
Please check the gap between select field and education type box . and check all input fields borders in safari

![image](https://cloud.githubusercontent.com/assets/11813145/19996742/be00087c-a287-11e6-9273-4c5a58e8ae94.png)

**Comment by NaziniSK** [comment]
gap between select field and education type box is corrected

**Comment by sanndheep5005** [comment]
Ok

**Comment by NaziniSK** [comment]
UI alignments also corrected , please close if resolved
