### ISSUE TITLE
Add Consultant  Education Type is adding multiple times

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#58]
Education Type is adding multiple times

![image](https://cloud.githubusercontent.com/assets/23167576/20002013/a232808a-a2a4-11e6-9cdf-3f5af5fe754b.png)

**Comment by NaziniSK** [comment]
corrected this issue please verify

**Comment by NaziniSK** [comment]
UI issues corrected in consultant page

**Comment by mounikaalladi** [comment]
Education Type sometimes adding multiple times
![image](https://cloud.githubusercontent.com/assets/23167576/20886832/eefb0752-bb1d-11e6-9c11-494468a3ff57.png)

**Comment by mounikaalladi** [comment]
its working
