### ISSUE TITLE
profile icon not displaying in header

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#6]
my profile icon is not displaying

![image](https://cloud.githubusercontent.com/assets/11813145/19888201/3146d7fc-a053-11e6-94ae-232d140395c8.png)

**Comment by NaziniSK** [comment]
It is not icon,if u have any profile picture ,it will be added there

**Comment by sanndheep5005** [comment]
ok , the profile image is so small please make it big and align with icons and when we are placing cursor on that pls check the background .

**Comment by NaziniSK** [comment]
Its not icon its image, if u upload small image it will come like this. it depends on the image u uploaded.

![image](https://cloud.githubusercontent.com/assets/23185953/19958193/42bceb7c-a1c3-11e6-8372-fb5647144708.png)
this is correct size.

![image](https://cloud.githubusercontent.com/assets/23185953/19958207/5b65b4f6-a1c3-11e6-9faa-ef7491cb8527.png)

**Comment by sanndheep5005** [comment]
ok now i have uploade a image size of 1200 \* 600 so i am gettting a error saying that unable to save file . So please there should be a validation saying image size should be this much of width and height

![image](https://cloud.githubusercontent.com/assets/11813145/19959585/e43309fa-a1cd-11e6-8cd5-09559640588d.png)
