### ISSUE TITLE
Invoice module is not shown up

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#60]
I have logged in as VASuperAdmin and Invoice is not showing up. I have also tried adding by clicking "+" icon. I dint get any page.

![image](https://cloud.githubusercontent.com/assets/20394163/20004163/b8629032-a2b0-11e6-97fe-d9da5e0bacd8.png)

**Comment by bhargavibindhu** [comment]
The same is checked with Mounika and the pages are visible like below.

![image](https://cloud.githubusercontent.com/assets/20394163/20004301/7e6fb264-a2b1-11e6-8c28-654ee9d01edd.png)

**Comment by NaziniSK** [comment]
please wait until grid is loaded then click on + button...
