### ISSUE TITLE
Vendor Add while Adding the  file Attachment 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#61]
Vendor Add While Adding the file  attachment it dispaying the message like invalid Extension but also its allowing to queue..(ODT And PNG files)

![image](https://cloud.githubusercontent.com/assets/23167576/20003909/0e14ef0e-a2af-11e6-96b4-c0b7a21e4016.png)

Vendor Add While deleting the attached file it not deleting ( X ) mark is deleting and Files are displaying.

![image](https://cloud.githubusercontent.com/assets/23167576/20004003/a584d4ee-a2af-11e6-9fb5-c9e5fe9061c9.png)

**Comment by NaziniSK** [comment]
corrected this

**Comment by mounikaalladi** [comment]
please refer to comment of #1 Id 
 The format should be same for all file uploads

**Comment by NaziniSK** [comment]
we changed as per that format

**Comment by mounikaalladi** [comment]
Reference #17  When u upload an attachment it s not saving .

**Comment by NaziniSK** [comment]
Please check Now

![image](https://cloud.githubusercontent.com/assets/23185953/20133826/090632a0-a68f-11e6-8137-cfab4926022a.png)

**Comment by bhargavibindhu** [comment]
The form is getting saved but there is no success message "Your data is saved" especially when you add vendor. On the contrary i am getting a red notification with no error message on it. Screenshot below.

**Comment by sanndheep5005** [comment]
![image](https://cloud.githubusercontent.com/assets/11813145/20208259/ee72c75c-a812-11e6-94fa-d61df20d3074.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20209069/3a44b01e-a818-11e6-978f-dbd84d9cfa17.png)
it got saved for me.

**Comment by mounikaalladi** [comment]
**Every time if i refresh the page the doc is saved.**

I have attached css interview Questions PDF i got blank error message.
![image](https://cloud.githubusercontent.com/assets/23167576/20301754/a16a85cc-ab4a-11e6-97e3-74ea31a8481a.png)

I have refreshed the page and again added same document then it is saved . 

![image](https://cloud.githubusercontent.com/assets/23167576/20301773/bd4f2888-ab4a-11e6-976e-7db26d3612ff.png)

**Comment by NaziniSK** [comment]
corrected this issue

**Comment by mounikaalladi** [comment]
Vendor edit is not saving while deleting the skill 

![image](https://cloud.githubusercontent.com/assets/23167576/20479615/e2c354b8-b004-11e6-87d8-5a08f49b804f.png)

![image](https://cloud.githubusercontent.com/assets/23167576/20479638/fa875ea0-b004-11e6-9c58-599b365c27e0.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20482747/46e0b670-b014-11e6-98f6-16eb0fb758d4.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20482758/569c68ca-b014-11e6-960a-6032950322f4.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20482762/5e2d3754-b014-11e6-8f42-79fb277a0431.png)

corrected this issue

**Comment by mounikaalladi** [comment]
In Super Admin Vendor Add

Entered  a new skill and added it and after i removed the skill it showed a popup box (are u sure u want to delete a skill ) then i clicked yes . 
It deleted and while adding same skill it showing an error message  as  skill already exists.

![image](https://cloud.githubusercontent.com/assets/23167576/20833015/6c85cda0-b8b3-11e6-8d9c-b4cd6a2975aa.png)

In vendor Admin Consultant add 

In skills i added  big data and then i deleted .
when i tried to add it again Big data is not added and  not displayed in skill under the skill box and  also it is displaying as cannot add duplicate entries for skills.

![image](https://cloud.githubusercontent.com/assets/23167576/20833092/cae6e9ec-b8b3-11e6-98ff-5a7636ce0399.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20882014/01133126-bb05-11e6-86a1-143c761f191f.png)
I added one skill by name c# then clicked on delete after confirmation message , I clicked on ok it got deleted.
![image](https://cloud.githubusercontent.com/assets/23185953/20882014/01133126-bb05-11e6-86a1-143c761f191f.png)
now again I added same skill, it got added for me without any issues,
![image](https://cloud.githubusercontent.com/assets/23185953/20882090/45bbd33c-bb05-11e6-90a6-f94094bc5c1c.png)

**Comment by sanndheep5005** [comment]
1) upladed a file and saved
![image](https://cloud.githubusercontent.com/assets/11813145/20887257/e95e807e-bb1f-11e6-9fdf-e45ffa449e29.png)

2) deleted the file ![image](https://cloud.githubusercontent.com/assets/11813145/20887274/f0d851ea-bb1f-11e6-9264-fcd1ddbf0d6b.png)

3) After deleting file still we can see dailystatus.dox                                                                                            ![image](https://cloud.githubusercontent.com/assets/11813145/20887287/fdb9e2ca-bb1f-11e6-8367-15f62bc8fe07.png)

4) once again i have uploaded a file but file is not attached 
 ![image](https://cloud.githubusercontent.com/assets/11813145/20887295/060200de-bb20-11e6-9f0a-d02fabbc7ea9.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20887312/124874e0-bb20-11e6-8ced-9716d78de6a2.png)

**Comment by mounikaalladi** [comment]
Vendor add While adding skill i added skill and again it toast please add skill 

![image](https://cloud.githubusercontent.com/assets/23167576/21010159/9aa22456-bd70-11e6-9b7e-60c44dcf8181.png)

**Comment by NaziniSK** [comment]
this is not error,this is info message and It will come if u click on plus icon without typing anything in skill box.

**Comment by mounikaalladi** [comment]
ok

**Comment by mounikaalladi** [comment]
its working
