### ISSUE TITLE
Online Users and Chat module

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#62]
Online users are not seen. Can you please check with this?

**Comment by sandipkumarnandi** [comment]
Bhargavu, is there any way we can categorize the bugs as bugs/queries ?

Online users are based on permission/hierarchy to which vendor/client they are mapped. not every one in the system can chat with every one.

**Comment by bhargavibindhu** [comment]
Can you please share the credentials for which I can check the chat functionality

**Comment by bhargavibindhu** [comment]
Chat details testing
[12:46:05] Blore-Sandeep: Consultant - VEndorEmployee
[12:47:55] Blore-Sandeep: DMeghana - Consultant - 12Test@1234@
[12:49:25] Blore-Sandeep: Mike1234- consultant- 12Test@1234@
[12:49:45] Blore-Sandeep: Consultant-Consultant (within a project)
[12:50:05] Blore-Sandeep: within the same client
[12:50:15] Bhargavi Moorthy: ok
[12:51:36] Blore-Sandeep: GauthamiKV - ClientAdmin - 12Test@1234@
[12:52:56] Blore-Sandeep: Mike1234 is vendor admin
das - vendor employee - 12Test@1234@

**Comment by bhargavibindhu** [comment]
I tried with DMEghana to chat with the other users shared above. I am not able to see the list in "online users" for the above users (except DMeghana). So discussed please show me a demo.

**Comment by bhargavibindhu** [comment]
![image](https://cloud.githubusercontent.com/assets/20394163/20091441/cc00ddfa-a5b8-11e6-91ce-0d99dd2bbedb.png)

![image](https://cloud.githubusercontent.com/assets/20394163/20091449/d66d602e-a5b8-11e6-93f4-b81ce03a85af.png)

**Comment by bhargavibindhu** [comment]
I tested this again today. I am looking for a 2 way communication chat say -  Person A texts something and it appears in Person B's chat window and Person B responds back and on. Currently i do not find this implemented. Can you please arrange a demo and help me with this feature?

Eg: Username: indukv's and DMeghna's screen (shared by you over mail)

![image](https://cloud.githubusercontent.com/assets/20394163/20165833/a2f3cb82-a736-11e6-9857-43b8f54975b0.png)

![image](https://cloud.githubusercontent.com/assets/20394163/20165850/c176bab0-a736-11e6-971a-0d6c669d5896.png)

**Comment by bhargavibindhu** [comment]
Karteekcon and Satyamclient are 2 users in which satyamclient is client and karteekcon is a consultant working for same project.

satyamclient has sent messages to karteekcon. But the message is not received in karteekcon's chat.

**## Satyamclient chat window:**
![image](https://cloud.githubusercontent.com/assets/20394163/20213328/3dddb174-a82e-11e6-8cb1-30041502500e.png)

**## Karteekcon online users:**
![image](https://cloud.githubusercontent.com/assets/20394163/20213365/60733eca-a82e-11e6-9720-332ec5710846.png)

**Comment by NaziniSK** [comment]
Please be informed that login name is case sensitive. I suspect that is causing the issue. Could you please login with "karteekCon" and try?

**Comment by bhargavibindhu** [comment]
i logged in with username as "karteekCon" only.

**Comment by NaziniSK** [comment]
Please check top right corner of the last image you sent.  Message is "Welcome karteekcon". Please give C as capital while logging. Do not hesitate to inform if you still face the issue.

**Comment by bhargavibindhu** [comment]
Holding this ticket for observation

**Comment by bhargavibindhu** [comment]
Holding this ticket for observation

**Comment by bhargavibindhu** [comment]
Can the SuperAdmin see the online users and chat with the vendors/clients/consultants?

**Comment by sandipkumarnandi** [comment]
At this point we have not given any access to SuperAdmin, but you need we can give access.

 

/Sandip

**Comment by bhargavibindhu** [comment]
If SuperAdmin is not given access for chat, why does the link exists in left menu? Please justify.

**Comment by sandipkumarnandi** [comment]
Chat window’s behavior is different from other menu items, so please do not consider that along side other menu items.

 

Chat window was earlier on right hand side, after discussion with Rajashekar we included that under the menu.

 

Again as I said the permission are dynamic in nature which can be enabled going further later through Admin Console.

 

/Sandip

**Comment by bhargavibindhu** [comment]
The point is not how it is working. It is about the option available in the VASuperAdmin login. We need to discuss this tomorrow.

**Comment by bhargavibindhu** [comment]
As per the discussion with Sandeep, SuperAdmin has no chat option and reference made in the below screen. So please remove the link for SuperAdmin

![image](https://cloud.githubusercontent.com/assets/20394163/21260600/bc4e3076-c3ac-11e6-9914-5304d277980a.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21262668/974187a4-c3b8-11e6-92ef-e521fa431269.png)
removed
