### ISSUE TITLE
Logo click

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#63]
When i click the logo it takes me to the below page.

![image](https://cloud.githubusercontent.com/assets/20394163/20005158/89acd364-a2b6-11e6-8879-7ee84ffdf92d.png)

**Comment by NaziniSK** [comment]
corrected this

**Comment by bhargavibindhu** [comment]
The link on the logo has been removed. Please do not remove the link.

On clicking Logo, it should take us to the homepage or the landing page that come after login. Please do the needful.

**Comment by NaziniSK** [comment]
ok

**Comment by NaziniSK** [comment]
added, please check in next deployment

**Comment by bhargavibindhu** [comment]
Please implement it in all the pages. When i am in edit page of client it is not working. 
Eg: http://va.antronsys.com/VAModule/Client/AddEditClients/44

**Comment by NaziniSK** [comment]
Please check now

**Comment by bhargavibindhu** [comment]
Closing it for now. Will reopen if this is occurring again.
