### ISSUE TITLE
Vendor detail page

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#64]
In Vendor detail page, the attachments are listed. But I am not able to view or download the attachment.
Please make the attachments readable with links.

![image](https://cloud.githubusercontent.com/assets/20394163/20048921/d2d8e952-a4e5-11e6-8d13-af7a2033d26c.png)

**Comment by NaziniSK** [comment]
this is just a listing page.

**Comment by bhargavibindhu** [comment]
But the attachment should be viewed to know what is uploaded in it. So Please do the needful.

**Comment by sandipkumarnandi** [comment]
Bhargavi, All views are just readonly without any actions, for download you need to go to Add/edit only

**Comment by bhargavibindhu** [comment]
Yes agreed it is just read-only. And hence referring the attachment file to be readable. This is the important point of having the "attachment" entity here. By just viewing the filename, the user has nothing to do here. It makes more sense if the file is readable.

**Comment by sandipkumarnandi** [comment]
Bhargavi,

  We can look into this as enhancements.

/Sandip

**Comment by bhargavibindhu** [comment]
This is a basic feature to be implemented in read mode and hence I am sorry to say that I differ from your point here. Sandip, we shall discuss over call to finalize it.

**Comment by bhargavibindhu** [comment]
This is a basic feature to be implemented in read mode and hence I am sorry to say that I differ from your point here. Sandip please call me if you have any issues with this,

**Comment by sandipkumarnandi** [comment]
Sorry Bhargavi,

  This is just a readonly screen, hence the attachment (which is an internal object) is not accessible. In case you need this to available for download, this has to be taken separately as special case.

 

 

  

 

/Sandip

**Comment by bhargavibindhu** [comment]
Is there any other place where the user can see the attachments?

**Comment by sandipkumarnandi** [comment]
Yes on the Edit page the user can download the attachment

 

/Sandip

**Comment by bhargavibindhu** [comment]
While referring the attachments in the detail page, the file should be clickable. It is NOT a good practice rather meaningless to show the filename without linking the file. 
Giving you reference in other sites: 
http://www.subzero-wolf.com/trade-resources/product-specifications/product-specifications-detail-page?name=36-inch-built-in-over-under-refrigerator-freezer-dispenser
=> check for the Guide

https://www.sofa.com/shop/sofas/sofabeds/whitby-sofabed/ 
=> Check for the techy specs

So please implement the same in Vendor detail page as well.

**Comment by sandipkumarnandi** [comment]
Bhargavi,

Every site has their own way of presenting things, that includes how the things are seen.

 

We can talk on this.

 

 

/Sandip

**Comment by bhargavibindhu** [comment]
You can give me one example of a site which shows the filename rather than the filename with link. It is really STRANGE and unacceptable.

**Comment by sandipkumarnandi** [comment]
Please park this as enhancement, we can take that after the UAT.

**Comment by bhargavibindhu** [comment]
You can give me one example of a site which shows the filename rather than the filename with link. It is really STRANGE and unacceptable. This is not an enhancement.

**Comment by sandipkumarnandi** [comment]
Please note this page is for print purpose, where the link or download facility will not have any relevance, hence the same was not included, however if you insist we will give it a thought.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21601480/4006f008-d1b1-11e6-81ee-7bcd02606afd.png)
added file download option
