### ISSUE TITLE
Vendor Edit is not saving But Successfully Sent Mail

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#65]
Vendor Edit  is not saving while editing and registration link is sending .
![image](https://cloud.githubusercontent.com/assets/23167576/20048914/ca16bc40-a4e5-11e6-9108-b11056c1a8a2.png)

![image](https://cloud.githubusercontent.com/assets/23167576/20049024/7fd1a748-a4e6-11e6-9831-12323c4f87aa.png)

**Comment by NaziniSK** [comment]
check with new one

**Comment by NaziniSK** [comment]
I corrected code today afternoon

**Comment by mounikaalladi** [comment]
Not working Same issue araised Without saving the record The mail has been sent 

![image](https://cloud.githubusercontent.com/assets/23167576/20129643/3143c2ea-a677-11e6-87ff-49d8c43bd32a.png)

**Comment by mounikaalladi** [comment]
First  attempt it worked but Second attempt it is not working . so , we keep it in observation.
![image](https://cloud.githubusercontent.com/assets/23167576/20177003/8813c88c-a770-11e6-9499-bebcdf478638.png)

**Comment by NaziniSK** [comment]
We tested and confirmed that it works fine.

Following is the screenshot when tried to send mail before saving

![sendbeforesave](https://cloud.githubusercontent.com/assets/23185953/20421020/5a655e88-ad87-11e6-9f60-fac53d383a2d.PNG)

Then I saved the record

![saved](https://cloud.githubusercontent.com/assets/23185953/20421029/67e377ac-ad87-11e6-94f7-d76a6c8c77bb.PNG)

After saving mail sending worked.

![sent](https://cloud.githubusercontent.com/assets/23185953/20421032/7494b47a-ad87-11e6-80bd-f7fa0d30fbb8.PNG)

Please test this again and verify

**Comment by NaziniSK** [comment]
Only in add case after successful saving of record mail will be sent. 
but in edit case . save is different , sending mail is different actions because whether the record is saved or not but mail will be sent based on already saved data.
also corrected save issue in edit case
