### ISSUE TITLE
client add

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#66]
In client creation choose file and bottom filename box are overlapping and there is a border for choose file option

![image](https://cloud.githubusercontent.com/assets/11813145/20048302/9e32a9b2-a4e1-11e6-8a30-aa56a16d010c.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20048663/3669fa9e-a4e4-11e6-8613-fe64f5530c2a.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20048824/45535e5a-a4e5-11e6-94ab-3513f34bc560.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20048998/53c21c14-a4e6-11e6-8041-4498ac8faef8.png)

**Comment by NaziniSK** [comment]
This one is corrected
