### ISSUE TITLE
To Reset password the mail was not Coming 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#67]
![image](https://cloud.githubusercontent.com/assets/23167576/20049120/14306cda-a4e7-11e6-8ff6-d3646f81e542.png)

I didnt Get any Mail to reset password .Waited 5 mins .

**Comment by mounikaalladi** [comment]
Again i tried with this login name  again same error vendor login 

![image](https://cloud.githubusercontent.com/assets/23167576/20051571/babefc8e-a4f5-11e6-8c17-a0d8fa102888.png)

**Comment by NaziniSK** [comment]
is this issue still persisting?

**Comment by mounikaalladi** [comment]
again i tried with another user again same issue is raising for me not gentting RESET PASSWORD link to my account gmail
![image](https://cloud.githubusercontent.com/assets/23167576/20054453/0e6986f8-a503-11e6-828e-d95c823f54be.png)

**Comment by NaziniSK** [comment]
verify with different emails

**Comment by NaziniSK** [comment]
and same email with different login

**Comment by bhargavibindhu** [comment]
Will wait and see this to work as expected for the next 2 days, then we can close this. Lets hold on this issue.

**Comment by bhargavibindhu** [comment]
This issue is not happening now, and hence closing it. Will reopen it if this is observed again.
