### ISSUE TITLE
Duplicate Login Username should be restricted

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#68]
I have edited a vendor and updated the login name as VASuperAdmin.  
I got the error message saying - "User with similar login name already exists. Please try with some other login name". Simultaneously I also get the success message - "You data is saved." which is contradictory.

Login username should be unique and there cannot be any duplicates. Please fix it.

![image](https://cloud.githubusercontent.com/assets/20394163/20050376/0b953242-a4ef-11e6-9039-e49571b24271.png)

**Comment by NaziniSK** [comment]
its restricting in service, if you pass like this it won't be saved. 

![image](https://cloud.githubusercontent.com/assets/23185953/20052707/3bc80f46-a4fb-11e6-877a-608227fb016d.png)

we are showing a message to user if existing login names are entered. if still user enters existing login name  that record wont be saved. If any record is saved please give me those details .

**Comment by bhargavibindhu** [comment]
Yes it is saved, please find the screenshot of Aspire Systems which is saved. 
Vendor id: #35-Aspire Systems it is saved.

![image](https://cloud.githubusercontent.com/assets/20394163/20052973/6d268eae-a4fc-11e6-9138-ea36944531c5.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20053783/1ff6cb7c-a500-11e6-87f5-8a66d6a6b53c.png)

**Comment by bhargavibindhu** [comment]
It is mentioned that the id is 35. Firstname is Sara. Please check the image i have attached.

**Comment by NaziniSK** [comment]
this is corrected , it will show message like this if user is saved with duplicate login name
![image](https://cloud.githubusercontent.com/assets/23185953/20166364/55cf5854-a73a-11e6-9cfe-f783f2bc9e12.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20166438/c4cd64ee-a73a-11e6-9023-e34a5f98dc6c.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20166585/d1b151a6-a73b-11e6-8b54-ad3819095989.png)

**Comment by bhargavibindhu** [comment]
This is not fixed, please check it. 

![image](https://cloud.githubusercontent.com/assets/20394163/20213233/85c186ba-a82d-11e6-93de-5f88272f94bf.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20216340/fcd8213e-a83f-11e6-9e18-88bd3fd078dd.png)
in edit case we are not allowing to change login name , made it one time entry for security reasons

**Comment by bhargavibindhu** [comment]
This issue is not happening now, if it occurs again will reopen this ticket.
