### ISSUE TITLE
Edit Consultant Joining and Expiry Date issue

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#69]
![image](https://cloud.githubusercontent.com/assets/23167576/20049866/d2c60df4-a4eb-11e6-8414-8a5e6d499568.png)

Joining Date and Expiry Date should not same and whit editing the contrct expiry date its saving the completed date is saving

**Comment by NaziniSK** [comment]
corrected this please check

**Comment by mounikaalladi** [comment]
in real scenario the contract cud be as less as 3 days

![image](https://cloud.githubusercontent.com/assets/23167576/20092614/2343face-a5bf-11e6-8885-c26b6e94b0b4.png)

**Comment by NaziniSK** [comment]
Logically expiry date should be greater than joining date and the system validate that.

**Comment by mounikaalladi** [comment]
@nareshpullakandam Can you please provide us the details to validate this?
