### ISSUE TITLE
help icon background 

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#7]
when we hover on help icon background color is not displaying full like notifications and messages background

![image](https://cloud.githubusercontent.com/assets/11813145/19888441/aa2bd28e-a054-11e6-8d4e-ab51f9fbe588.png)

**Comment by NaziniSK** [comment]
corrected this.pls..check now

![image](https://cloud.githubusercontent.com/assets/23185953/20138799/7f2a91ba-a6a8-11e6-9111-28ca0f3e01c8.png)
