### ISSUE TITLE
login error text should be highlighted

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#70]
when we are wrong username r password we r getting a text displaying  entered username r psswrd is incorrect . The text should be highlited     
![image](https://cloud.githubusercontent.com/assets/11813145/20050540/e861cf82-a4ef-11e6-9c61-362088f3f9fa.png)

And for forgot password also the text should be highlited( Please check ur mail box for further instructions)
![329eeefb3a8dddbdee47b8302bfff2093e998724405721cc07 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11813145/20051293/4c1748b4-a4f4-11e6-8c51-0fb5a58cfb8e.png)

**Comment by NaziniSK** [comment]
Previously this was highlighted with a border , but  it was raised ad bug (#39 ).So we removed that ,  highlight means is it enough if we change text colour?

**Comment by sanndheep5005** [comment]
ok change text color

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20057895/2189d330-a514-11e6-8b93-8ec152024fd4.png)
if I add like this will it be ok?

**Comment by NaziniSK** [comment]
I added please verify and close if resolved
