### ISSUE TITLE
cancel button is not working

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#72]
![image](https://cloud.githubusercontent.com/assets/23167576/20053565/28ec455a-a4ff-11e6-9d23-8f7f7cc632e5.png)

**Comment by NaziniSK** [comment]
corrected this

on click of cancel
![image](https://cloud.githubusercontent.com/assets/23185953/20089141/e22b50aa-a5aa-11e6-9eb7-2c8e8ae823f7.png)

it will redirect to previous page

![image](https://cloud.githubusercontent.com/assets/23185953/20089155/efabca48-a5aa-11e6-998a-1a9d1aefb283.png)
