### ISSUE TITLE
User profile is not saved

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#73]
I tried to update few fields in the User profile page, it is not getting saved, 
http://va.antronsys.com/VAModule/UserProfile

User profile image uploaded is also not saved.

**Comment by NaziniSK** [comment]
Admin should Approve User Profile. Then only it will save.

**Comment by bhargavibindhu** [comment]
As seen over the skype call with screen share, the profile page sometimes is not working and it is issuing error like below.

![image](https://cloud.githubusercontent.com/assets/20394163/20090681/ac67e118-a5b4-11e6-9972-4fdabab45202.png)

**Comment by bhargavibindhu** [comment]
As seen over the skype call with screen share, the profile page is approved by the Main admin but still the changes are not reflected in the profile page. 

Main admin page:

![image](https://cloud.githubusercontent.com/assets/20394163/20090728/ebf8f8d0-a5b4-11e6-9f8d-ced42dab5a34.png)

User profile page:
![image](https://cloud.githubusercontent.com/assets/20394163/20090736/f913dd5a-a5b4-11e6-83d0-bc93bc20f031.png)

**Comment by NaziniSK** [comment]
this issue is corrected 
![image](https://cloud.githubusercontent.com/assets/23185953/20100330/066cd636-a5e3-11e6-9fa0-7688ffc142ab.png)
![image](https://cloud.githubusercontent.com/assets/23185953/20100336/1421ac48-a5e3-11e6-8547-042280151790.png)

**Comment by bhargavibindhu** [comment]
I changed all the fields in this page. But not all are getting saved. Can you please check once again and fix it?

**Comment by NaziniSK** [comment]
Please check now it's working for us

![image](https://cloud.githubusercontent.com/assets/23185953/20133426/7dac0c44-a68d-11e6-9379-2b7765f9b3a7.png)

**Comment by bhargavibindhu** [comment]
I repeat this - https://github.com/acsestech/virtualassociate/issues/73#issuecomment-259352277
Not all fields are saved esp i tried to add date of birth and joining date. It is not saved.
