### ISSUE TITLE
Activate and Inactivate users list

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#74]
Inactive users list is not showing up properly, please find the below screen.

![image](https://cloud.githubusercontent.com/assets/20394163/20097107/d33b11ca-a5d2-11e6-8570-93245f0dab34.png)

Steps to reproduce:
1. Login as VASuperAdmin
2. Click Vendors and the list of active users are displayed from 1 to 10
3. Click "show inactive records". Below screen is seen.
![image](https://cloud.githubusercontent.com/assets/20394163/20097161/102fbdc4-a5d3-11e6-8f59-b0b64c681d85.png)
4. Click "Show Active Records" and this will list the vendor active users as seen in step 2.
5. Now click the next button to show 11 to 20
6. Now repeat step 3 - the issue is clearly visible.

The user list should be maintained, please fix this.

**Comment by NaziniSK** [comment]
Corrected this one, please confirm and close
