### ISSUE TITLE
Vendor Employee Access Over Consultant 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#75]
When vendor Employee Logged in he can only view the consultants .

![image](https://cloud.githubusercontent.com/assets/23167576/20098261/f9bb77c6-a5d8-11e6-9d8f-e16d6d87ddc4.png)

**Comment by NaziniSK** [comment]
![untitled](https://cloud.githubusercontent.com/assets/23185953/20133954/9aeceb50-a68f-11e6-8c95-de45030e5f97.png)
![capture](https://cloud.githubusercontent.com/assets/23185953/20133978/b0943396-a68f-11e6-806b-950b913a5d39.PNG)

**Comment by NaziniSK** [comment]
Corrected this bug

**Comment by mounikaalladi** [comment]
Please Hide all the buttons which are not allowed ()

**Comment by NaziniSK** [comment]
Okay, We are taking this as a suggestion. We'll do this later.

**Comment by sanndheep5005** [comment]
vendor employee cannot  create a consultant on 11-11-16 while creating a consultant by vendremployee i got a popup that vendoremp has no permission to create .But today i tried to create i am able to create consultant.

![image](https://cloud.githubusercontent.com/assets/11813145/20257069/4ebf0088-aa6d-11e6-8c5e-c3a0fcd1b392.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20257082/6480870c-aa6d-11e6-88c2-613d228a876f.png)

**Comment by NaziniSK** [comment]
We tested this issue in different browsers for different logins. It is not reproducing. It can be caching problem at your end. Another possibilty is some one would have made rohan5Vemp a vendor. (from vendor add edit page). Please clear cache and try again.

**Comment by mounikaalladi** [comment]
Refer #31

**Comment by mounikaalladi** [comment]
inactive Button if not required it can be removed 

![image](https://cloud.githubusercontent.com/assets/23167576/20344923/af7cb2d6-ac1a-11e6-9590-e8ecc922d80f.png)

**Comment by NaziniSK** [comment]
Removing buttons will be considered as enhancement for the project and will be taken later if you wish to add them. Now we are giving a toast as in given message and further operations are stopped.

Please check and confirm.

![ve](https://cloud.githubusercontent.com/assets/23185953/20377374/f9406238-acb4-11e6-94d6-a2a764e38cf7.PNG)

**Comment by mounikaalladi** [comment]
Consultants list also should not be  seen to vendor Employee login  ah..?? only online users Showing in the 
login
![image](https://cloud.githubusercontent.com/assets/23167576/20752421/5c0f93e4-b727-11e6-8a3a-47aa555c29c1.png)

**Comment by mounikaalladi** [comment]
Vendor Employee login cannot see the list of consultants

![image](https://cloud.githubusercontent.com/assets/23167576/20830984/12198334-b8a9-11e6-8f35-babec3d7d214.png)

**Comment by NaziniSK** [comment]
this is not reproducing now

**Comment by mounikaalladi** [comment]
i will check.

**Comment by mounikaalladi** [comment]
its working 

![image](https://cloud.githubusercontent.com/assets/23167576/21260662/120fe522-c3ad-11e6-9292-c34e76d87336.png)

**Comment by bhargavibindhu** [comment]
This is sporadic and intermittent. Will keep this bug rechecked at every stage. For now closing it and may reopen if this is happening again.
