### ISSUE TITLE
Mandatory fields should be marked in red

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#77]
In all the forms if the fields are mandatory, please mark the label in red. Eg: Project Add - Lead and description are not marked in red but it is mandatory. Please fix this in all the forms of VA.

**Comment by bhargavibindhu** [comment]
![image](https://cloud.githubusercontent.com/assets/20394163/20173944/88da248c-a761-11e6-977d-310bd2c74462.png)

**Comment by NaziniSK** [comment]
![projectaddedit](https://cloud.githubusercontent.com/assets/23185953/20177122/2c5d9dfa-a771-11e6-893f-189b049453ed.PNG)

Added required \* mark in project add edit

**Comment by bhargavibindhu** [comment]
This is not done for Consultant add and edit. Please implement it. REquest you to run through all the forms and fix it where ever required.

**Comment by NaziniSK** [comment]
As date of birth has special kind of validation (20 years or above), we were checking that before save and giving toast. Now that is changed.we did not add required (*) mark for joining date and end date in vendor details tab, as that is depending on resource provider selection. 

If resource provider is vendor, then only those fields are becoming mandatory. So, only for these fields we did not add \* symbols. Just before saving I m checking that through jquery code and giving a toast.  Please consider this as a special case

**Comment by bhargavibindhu** [comment]
Please give meaningful and user friendly error messages in all the forms. I am trying to save this form but I am getting an error "Invalid Client details". Can you tell me which is invalid entry here?

![image](https://cloud.githubusercontent.com/assets/20394163/20830190/683a413a-b8a5-11e6-9c3d-897d01c6ed5a.png)

**Comment by bhargavibindhu** [comment]
Referring to https://github.com/acsestech/virtualassociate/issues/85
