### ISSUE TITLE
Project Status, Client added this month, Vendor added this month

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#78]
In the dashboard the headers for Project Status, Client added this month, Vendor added this month should be fixed at the top of each table so that i can view it when i scroll down to the end of the records.

![image](https://cloud.githubusercontent.com/assets/20394163/20174444/ccd5fd08-a763-11e6-9308-f6a5a3ed20ff.png)

**Comment by NaziniSK** [comment]
corrected this please verify now

**Comment by bhargavibindhu** [comment]
Looks good, thanks

**Comment by sanndheep5005** [comment]
Dashboard page in Ie11
![image](https://cloud.githubusercontent.com/assets/11813145/20338554/cb1f4200-abfd-11e6-900f-2cc282bed785.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20338580/f37a9c9a-abfd-11e6-9b99-8ea80816092a.png)

**Comment by NaziniSK** [comment]
![dashboard](https://cloud.githubusercontent.com/assets/23185953/20380818/4ec0c1f2-acca-11e6-822b-e53336d7869d.PNG)

Corrected. Please check

**Comment by bhargavibindhu** [comment]
This is not fixed, please ensure the same.

**Comment by sanndheep5005** [comment]
Dashboard Issue in IE11 not yet fixed

![image](https://cloud.githubusercontent.com/assets/11813145/20830344/1d2b9d8c-b8a6-11e6-9bfe-9aa33667c433.png)

**Comment by NaziniSK** [comment]
![dashboard-edge](https://cloud.githubusercontent.com/assets/23185953/21515824/f820ead0-ccf8-11e6-995d-52504f70bd82.png)
![dashboard-ie](https://cloud.githubusercontent.com/assets/23185953/21515965/20d30f34-ccfa-11e6-94f3-7f2b800a16dd.png)
corrected this
