### ISSUE TITLE
Multiple record entries when assigning a consultant to the project 

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#79]
We encounter multiple record entries when assigning a consultant to the project, screen below for reference. 

![image](https://cloud.githubusercontent.com/assets/20394163/20174607/af8009a0-a764-11e6-9665-614fdaa2f128.png)

**Comment by NaziniSK** [comment]
![projectconsultant](https://cloud.githubusercontent.com/assets/23185953/20293825/794c9baa-ab1f-11e6-8222-27bb5e099c68.PNG)

Resolved this issue

If you try to add existing project consultant combination, you will get a toast as in the image.

Please check and verify

**Comment by bhargavibindhu** [comment]
This has led to another issue now!!! I am not able to assign new consultant to my project. 
And please change the status message - it is showing the IDs "59, 81" - not the right way to pop up in the message. 

![image](https://cloud.githubusercontent.com/assets/20394163/20296491/24fc68fc-ab31-11e6-97f0-173db6efb118.png)

**Comment by NaziniSK** [comment]
![projectconsultant](https://cloud.githubusercontent.com/assets/23185953/20303990/fffeed4a-ab53-11e6-8a99-4c799a52aab2.PNG)

Corrected this issue. Please check and confirm
