### ISSUE TITLE
Pagination not working for Vendor

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#8]
![image](https://cloud.githubusercontent.com/assets/23167576/19888452/b7a1335a-a054-11e6-894c-7777e4034c8b.png)

Pagination in listing of vendors  is not working and  showing only first 10 records when i click 20 0r 15  .

**Comment by NaziniSK** [comment]
Corrected this please wait for next deployment .

**Comment by mounikaalladi** [comment]
Thank Nazini Its working Now.
