### ISSUE TITLE
Tasks details are not displayed after Task assignment

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#81]
The task details are not displayed in the consultant page or in the client employee page, please do the needful. 

**## Screenshot taken from Client login:**

![image](https://cloud.githubusercontent.com/assets/20394163/20175462/d728e75c-a768-11e6-816b-f60c94b3a7dd.png)

**Comment by sanndheep5005** [comment]
**screen shot taken from consultant login**

![image](https://cloud.githubusercontent.com/assets/11813145/20175607/a5ad2bba-a769-11e6-9bef-43626be74376.png)

**Comment by NaziniSK** [comment]
consultant login

![image](https://cloud.githubusercontent.com/assets/23185953/20296267/e887ec30-ab2f-11e6-910e-1ebc2b2d12f6.png)

client login

![image](https://cloud.githubusercontent.com/assets/23185953/20296338/4622abe6-ab30-11e6-9d9d-d35e1163927b.png)

its working

**Comment by sanndheep5005** [comment]
please List out the steps to view the Task Assignment . We are not seeing any of the task when the client assigns any task to the consultant.

**Comment by sanndheep5005** [comment]
Unable to assign task . 
login name : gurunano
default pswrd

![image](https://cloud.githubusercontent.com/assets/11813145/20346422/e9b174c6-ac21-11e6-8159-d46175f221c4.png)

**Comment by bhargavibindhu** [comment]
can u please fix https://github.com/acsestech/virtualassociate/issues/81 with top priority as 
i am not able to check the tickets related to task assignment, timehset, billing, invoice etc...

**Comment by NaziniSK** [comment]
please check , is this issue still persists after today's deployment
