### ISSUE TITLE
Notification at the header

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#83]
The notification always shows 0 and it is empty all the time. Can you please work on this?

![image](https://cloud.githubusercontent.com/assets/20394163/20256696/155a5358-aa6b-11e6-90de-04574881f539.png)

**Comment by NaziniSK** [comment]
if any notifications will come then only it is populated. right now for this user there are no notifications.

**Comment by bhargavibindhu** [comment]
Even if the User profile Approval is pending, the notification is zero. 
Secondly, please list out what are the other notifications that will be listed out in this space.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20295568/cdb307c2-ab2b-11e6-83a3-c891787a8cb8.png)
Profile update notifications will be shown in application messages

**Comment by bhargavibindhu** [comment]
Please read my comments again - i have mentioned as approval of user profiles
https://github.com/acsestech/virtualassociate/issues/83#issuecomment-260557211

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20304255/45f47e04-ab55-11e6-98a8-fa6afe78d7a5.png)
corrected this , for now we are not using anywhere else for super admin login

**Comment by bhargavibindhu** [comment]
Secondly, please list out what are the other notifications that will be listed out in this space.

**Comment by mounikaalladi** [comment]
when I clieck the i tems in the notification it should redirect to coorresponding user profile. but i am getting # in the URL (http://va.antronsys.com/Platform/ApprovalUserProfile#;)
![image](https://cloud.githubusercontent.com/assets/23167576/20749000/81d4caec-b716-11e6-98a8-91740de3514d.png)

**Comment by NaziniSK** [comment]
this is not a bug, its just notification , on click of that notification it is  saved as read notification ,no redirection added. 
it should redirect to corresponding user profile-this is not there in requirement

**Comment by bhargavibindhu** [comment]
https://github.com/acsestech/virtualassociate/issues/83#issuecomment-263843151 says there is a requirement doc, please share the same.

**Comment by bhargavibindhu** [comment]
The notification count is not getting updated. When I read the notification, again it is showing "New Notification". Please fix this.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21262772/19ce356e-c3b9-11e6-92c1-9a4a37caa084.png)
its fixed
