### ISSUE TITLE
Approve Profile feature

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#84]
Approve profile feature lists out all the records that are pending for approval.
1. Issue 1: There is only "Approve Changes" option in this page. If the admin has to reject the change, how is this addressed?
2. Issue 2: The Admin approves profile changes and it is saved. But if the admin logins again, even the Approved user profiles are also listed in the pending approvals. Please fix this.

It is very difficult to identify and keep track of the changes made the user and the admin approvals. I prefer this page can be done like any other pages eg: vendor listing, client listing, consultant listing page etc.

**Comment by bhargavibindhu** [comment]
There are multiple issues in this functionality.
1. I do not have reject option if I have to reject a profile change. 
2. The approval entries are getting duplicated here.
3. I do not have any idea on how many records i have to approve. ( no count or no listing). 
4. This approval entries has to be listed one by one as seen in other pages.

**Comment by NaziniSK** [comment]
this is considering as enhancement , will do this later

**Comment by bhargavibindhu** [comment]
The current functionality is not baselined. Let us first fix it and then plan for enhancement. Points listed in https://github.com/acsestech/virtualassociate/issues/84#issuecomment-260577550 covers only the basic expected behaviour of the Approve user profile module. Request you to do the needful.

**Comment by bhargavibindhu** [comment]
Approve user profile is not working and triggers error. This is the known bug as per Sandips email.
Please fix it ASAP.

![image](https://cloud.githubusercontent.com/assets/20394163/20825633/76e116ec-b88b-11e6-8d5f-c4688991d1be.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20880363/c268caa0-bafd-11e6-9757-33b5b60c6804.png)

if current data is last one and you are clicking next ">" or if current data is first you are clicking previous 
"< ", then only this message is showing,otherwise it will show the records.

**Comment by bhargavibindhu** [comment]
if it is first or last record, disable the navigation. Try for some solution such that this error is happening.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21006702/186bf5bc-bd60-11e6-9ee0-e1d90e2d8b3a.png)
showing like this if no previous or next records found

**Comment by NaziniSK** [comment]
when you click on cancel it will take you to next record, and when you click on refresh it will show first or default record.

**Comment by bhargavibindhu** [comment]
Rename "Cancel" as "Next". 
Rename "Refresh" as "Go to First".
Place the buttons in the below order.
"Go to First", "Approve Changes", "Next"

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21262811/4b48db94-c3b9-11e6-8c99-3e8f4e8df959.png)
done
