### ISSUE TITLE
unable to add client employee

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#85]
Unable to add client employee 

![image](https://cloud.githubusercontent.com/assets/11813145/20257409/6bd7f150-aa6f-11e6-8ab6-6db5ed7148eb.png)

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20260627/8763a818-aa80-11e6-9a9c-3a849cfc2064.png)
saved for me

**Comment by sanndheep5005** [comment]
just now i tried to add

![image](https://cloud.githubusercontent.com/assets/11813145/20260790/30dc6a06-aa81-11e6-9e69-4e1b7bf7d26c.png)

**Comment by sanndheep5005** [comment]
cleared history and tried onceagain but unable

![image](https://cloud.githubusercontent.com/assets/11813145/20260988/f30566b4-aa81-11e6-8d24-0464935b4717.png)

**Comment by sanndheep5005** [comment]
In Client i am unable to see login name .But i am able to login with that login name

![image](https://cloud.githubusercontent.com/assets/11813145/20346288/43403d98-ac21-11e6-9806-cab5f8a58488.png)

**Comment by NaziniSK** [comment]
corrected this issue, Invalid client details message will come when tried to assign already assigned project.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20881148/f00a64de-bb00-11e6-9108-37618dcb4d45.png)

**Comment by NaziniSK** [comment]
if project is already assigned to other client it will show , message like above

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20881678/7bd5b606-bb03-11e6-938b-848bc92c98ed.png)


if any of "*" marked data is missing then it will show like this , as I missed phone number here

**Comment by NaziniSK** [comment]
![Uploading image.png…]()

if already existing login name is given then it will show like this
