### ISSUE TITLE
can save client details error msg in consultant page

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#87]
while adding a client in consultant page getting can save client details error message but details are saving

![image](https://cloud.githubusercontent.com/assets/11813145/20260328/22cf5f60-aa7f-11e6-947b-366a4c3887ce.png)

**Comment by NaziniSK** [comment]
![cc](https://cloud.githubusercontent.com/assets/23185953/20295288/1417a544-ab2a-11e6-880a-6f7c15fcf066.PNG)

Removed that error message. Please check and verify

**Comment by sanndheep5005** [comment]
unable to edit client details 

![image](https://cloud.githubusercontent.com/assets/11813145/20338301/3b8befea-abfc-11e6-9dfa-43abf182dac2.png)

**Comment by NaziniSK** [comment]
Corrected this issue. Please check

**Comment by bhargavibindhu** [comment]
The Contract expiry date should be greater than the joining date. Please do not enforce the expiry date to be greater than previous end date. The consultant may also be removed from the project before his contract period might be due his performance and other reasons. 
![image](https://cloud.githubusercontent.com/assets/20394163/20379564/f0f472b4-acc2-11e6-8684-dbd3894798a7.png)

**Comment by NaziniSK** [comment]
Removed that condition while editing consultant-client details. Please check.
