### ISSUE TITLE
project not displaying in consultant timesheet

### ISSUE THREAD

**Issue by sanndheep5005** [acsestech/virtualassociate#88]
project not displaying in consultant timesheet

![image](https://cloud.githubusercontent.com/assets/11813145/20261326/4e29b36e-aa83-11e6-8050-c1e218587f3c.png)

**Comment by NaziniSK** [comment]
This is shown based on consultant's client's default client employee projects and project consultant relation ship . if project is added in both the places then only it is shown here

**Comment by sanndheep5005** [comment]
I have added 4 projects to rohan5Con by the client rohan5Cnt

![image](https://cloud.githubusercontent.com/assets/11813145/20297736/f79670fe-ab37-11e6-93cf-e42dd3d97886.png)

But in rohan5Con i am able to see only one project in drop down

![image](https://cloud.githubusercontent.com/assets/11813145/20297797/52d4315e-ab38-11e6-80f4-043dbad89578.png)

**Comment by NaziniSK** [comment]
This project should be assigned to any client employee. Then only the project will be listed in consultant timesheets's project dropdown.

![clientemployee](https://cloud.githubusercontent.com/assets/23185953/20377234/c0014ab0-acb3-11e6-9ccf-9c7885e3a043.PNG)

**Comment by sanndheep5005** [comment]
the client has assigned 4 projects to consultant so in consultant time sheet 4 projects should display . Two days ago i was able to see one project and today i am able to see two projects.

![image](https://cloud.githubusercontent.com/assets/11813145/20377905/cb617718-acb8-11e6-8bb7-9a7892e4d1e0.png)

**Comment by NaziniSK** [comment]
From the given scrrenshots, I understand that consultant named rohan5Con is assigned with Android, MobileApp, webapp and mobileapp projects from Project Consultant UI.

If all these project needs to be displayed on Consultant time sheet, these projects should be assigned to any client employee for the given client.

Could you please check Android and webapp projects are assigned to any client employee ? 

You can assign project to client employee from client employee edit page. Please refer previous screenshot which I sent

**Comment by sanndheep5005** [comment]
Ok I got it I am trying to check but unable to save client details.

![image](https://cloud.githubusercontent.com/assets/11813145/20378709/c2f177cc-acbd-11e6-87ed-e3d1e265339a.png)

**Comment by mounikaalladi** [comment]
when i am assigning project (Mobile App to smitha) it toast message like ( project name :phone gap development and consultant name : smitha this combination aldready exists.

![image](https://cloud.githubusercontent.com/assets/23167576/20379877/8dec8c86-acc4-11e6-92f0-a51b15e7fba4.png)

**Comment by NaziniSK** [comment]
Corrected this. Please check and confirm

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/20879973/25a17f38-bafc-11e6-9c21-192300c9bc66.png)
client employee is saving without any issues.


![image](https://cloud.githubusercontent.com/assets/23185953/20880178/ddfc1d18-bafc-11e6-8aa9-1037fe698a59.png)

project consultant also saved, if same combination is repeated then it won't take, it will return error like below one

![image](https://cloud.githubusercontent.com/assets/23185953/20880201/f65707b0-bafc-11e6-956d-fb0e1286a919.png)
