### ISSUE TITLE
Client employee details to be viewed by admin

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#89]
I added a client employee newly from client admin login. 
I am not able to view this data either from VASuperAdmin or Main Admin. 
VASuperAdmin doesnt have the client employee list in his view at all.
When i click the client employee details shown in Main Admin, below is the screen i get.

![image](https://cloud.githubusercontent.com/assets/20394163/20263088/1aa4e45c-aa8b-11e6-927e-03457d66c775.png)

**Comment by NaziniSK** [comment]
super admin doesn't have permissions to view client employees as per requirement. This is not a valid bug
