### ISSUE TITLE
Timesheet save and submit

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#92]
Whenever i enter data in timesheet and click save / save and submit, i get an error like below.

![image](https://cloud.githubusercontent.com/assets/20394163/20424019/a374fd10-ad99-11e6-83ae-4f2f4426685a.png)

**Comment by sanndheep5005** [comment]
client assigned hours unable to see in Ie11 able to see in other browsers.

![image](https://cloud.githubusercontent.com/assets/11813145/20475099/e88acb3e-afef-11e6-8de1-ee3da22a0df0.png)

![image](https://cloud.githubusercontent.com/assets/11813145/20475106/f326683c-afef-11e6-9785-48985361bedc.png)
