### ISSUE TITLE
alignment issue while uploading file in Consultant Add

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#97]
![image](https://cloud.githubusercontent.com/assets/23167576/20748608/ddba479e-b714-11e6-9761-bba2da537b20.png)

**Comment by NaziniSK** [comment]
![resume](https://cloud.githubusercontent.com/assets/23185953/20963242/a51c8bda-bc92-11e6-8e61-c523a656ec0a.PNG)

Changed the alignment. Now resume is appended down.
