### ISSUE TITLE
Consultant Add module  #client details tab - edit icon is not working 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#98]
While adding consultant , data on Client Details are  unable to edit  ex : billing to client is empty while clicking edit icon 

![image](https://cloud.githubusercontent.com/assets/23167576/20748670/1a8e97a6-b715-11e6-8d51-69e0ccdc3956.png)

**Comment by mounikaalladi** [comment]
While edit icon billing to client was not editing
![image](https://cloud.githubusercontent.com/assets/23167576/20886629/070d8546-bb1d-11e6-9baf-11e71f3aba0d.png)

After trying to edit with another number like 200 i clicked enter then i got a popup box
![image](https://cloud.githubusercontent.com/assets/23167576/20886667/33018f6c-bb1d-11e6-8751-471971c4f5c7.png)

**Comment by NaziniSK** [comment]
![c1](https://cloud.githubusercontent.com/assets/23185953/20961120/a400dfe8-bc89-11e6-9173-58bc751934bf.PNG)

Issue you have mentioned in the first screenshot is not reproducing. We have resolved it earlier itself.

Popup issue mentioned in the second screenshot is resolved. Please check

**Comment by mounikaalladi** [comment]
![image](https://cloud.githubusercontent.com/assets/23167576/21259948/d60eb146-c3a9-11e6-8569-883777656985.png)
 its working
