### ISSUE TITLE
Arrange the dropdown items in Ascending order

### ISSUE THREAD

**Issue by bhargavibindhu** [acsestech/virtualassociate#99]
Arrange the dropdown items in Ascending order. Please check in all the dropdown this is maintained.
![image](https://cloud.githubusercontent.com/assets/20394163/20752402/43232288-b727-11e6-8aa8-1056ecff8443.png)

**Comment by NaziniSK** [comment]
this is enhancement

**Comment by bhargavibindhu** [comment]
Arranging cannot be taken as enhancement. Please implement it.

**Comment by NaziniSK** [comment]
![image](https://cloud.githubusercontent.com/assets/23185953/21003329/c55ead10-bd50-11e6-946a-0cc40e5822ec.png)
implemented
